package com.leonia.wellness.entity;

// Generated 20 Jul, 2016 3:39:07 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.Generated;
import org.hibernate.annotations.GenerationTime;

/**
 * Appointmentstockconsumption generated by hbm2java
 */
@Entity
@Table(name = "appointmentstockconsumption")
public class Appointmentstockconsumption implements java.io.Serializable {

	private int appointmentstockid;
	private Appointment appointment;
	private Packagemaster packagemaster;
	private Servicemaster servicemaster;
	private Stockmaster stockmaster;
	private int sno;
	private BigDecimal stockusage;
	private BigDecimal stockvalue;
	private boolean valid;
	private String updatedby;
	private Date updateddate;
	private String updatedip;

	public Appointmentstockconsumption() {
	}

	public Appointmentstockconsumption(int appointmentstockid,
			Appointment appointment, Stockmaster stockmaster, int sno,
			BigDecimal stockusage, BigDecimal stockvalue, boolean valid,
			String updatedby, Date updateddate, String updatedip) {
		this.appointmentstockid = appointmentstockid;
		this.appointment = appointment;
		this.stockmaster = stockmaster;
		this.sno = sno;
		this.stockusage = stockusage;
		this.stockvalue = stockvalue;
		this.valid = valid;
		this.updatedby = updatedby;
		this.updateddate = updateddate;
		this.updatedip = updatedip;
	}

	public Appointmentstockconsumption(int appointmentstockid,
			Appointment appointment, Packagemaster packagemaster,
			Servicemaster servicemaster, Stockmaster stockmaster, int sno,
			BigDecimal stockusage, BigDecimal stockvalue, boolean valid,
			String updatedby, Date updateddate, String updatedip) {
		this.appointmentstockid = appointmentstockid;
		this.appointment = appointment;
		this.packagemaster = packagemaster;
		this.servicemaster = servicemaster;
		this.stockmaster = stockmaster;
		this.sno = sno;
		this.stockusage = stockusage;
		this.stockvalue = stockvalue;
		this.valid = valid;
		this.updatedby = updatedby;
		this.updateddate = updateddate;
		this.updatedip = updatedip;
	}

	@Id
	@Column(name = "appointmentstockid", unique = true, nullable = false)
	public int getAppointmentstockid() {
		return this.appointmentstockid;
	}

	public void setAppointmentstockid(int appointmentstockid) {
		this.appointmentstockid = appointmentstockid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "appointmentid", nullable = false)
	public Appointment getAppointment() {
		return this.appointment;
	}

	public void setAppointment(Appointment appointment) {
		this.appointment = appointment;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "packageid")
	public Packagemaster getPackagemaster() {
		return this.packagemaster;
	}

	public void setPackagemaster(Packagemaster packagemaster) {
		this.packagemaster = packagemaster;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "serviceid")
	public Servicemaster getServicemaster() {
		return this.servicemaster;
	}

	public void setServicemaster(Servicemaster servicemaster) {
		this.servicemaster = servicemaster;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "stockid", nullable = false)
	public Stockmaster getStockmaster() {
		return this.stockmaster;
	}

	public void setStockmaster(Stockmaster stockmaster) {
		this.stockmaster = stockmaster;
	}

	@Generated(GenerationTime.INSERT)
	@Column(name = "sno", insertable = false, nullable = false)
	public int getSno() {
		return this.sno;
	}

	public void setSno(int sno) {
		this.sno = sno;
	}

	@Column(name = "stockusage", nullable = false, precision = 15, scale = 3)
	public BigDecimal getStockusage() {
		return this.stockusage;
	}

	public void setStockusage(BigDecimal stockusage) {
		this.stockusage = stockusage;
	}

	@Column(name = "stockvalue", nullable = false, precision = 15)
	public BigDecimal getStockvalue() {
		return this.stockvalue;
	}

	public void setStockvalue(BigDecimal stockvalue) {
		this.stockvalue = stockvalue;
	}

	@Column(name = "valid", nullable = false)
	public boolean isValid() {
		return this.valid;
	}

	public void setValid(boolean valid) {
		this.valid = valid;
	}

	@Column(name = "updatedby", nullable = false, length = 150)
	public String getUpdatedby() {
		return this.updatedby;
	}

	public void setUpdatedby(String updatedby) {
		this.updatedby = updatedby;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updateddate", nullable = false, length = 29)
	public Date getUpdateddate() {
		return this.updateddate;
	}

	public void setUpdateddate(Date updateddate) {
		this.updateddate = updateddate;
	}

	@Column(name = "updatedip", nullable = false, length = 150)
	public String getUpdatedip() {
		return this.updatedip;
	}

	public void setUpdatedip(String updatedip) {
		this.updatedip = updatedip;
	}

}
