package com.leonia.wellness.entity;

// Generated 10 Aug, 2016 6:51:03 PM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Appointmentservicedetails generated by hbm2java
 */
@Entity
@Table(name = "appointmentservicedetails", uniqueConstraints = @UniqueConstraint(columnNames = {"appointmentid", "serviceid" }))
public class Appointmentservicedetails implements java.io.Serializable {

	private int sno;
	private Appointment appointment;
	private Packagemaster packagemaster;
	private Roommaster roommaster;
	private Servicemaster servicemaster;
	private Staffmaster staffmaster;
	private Statusmaster statusmaster;
	private Date schappointdate;
	private String schappointtime;
	private Date actstartdate;
	private String actstarttime;
	private Date schdepartdate;
	private String schdeparttime;
	private Date actdepartdate;
	private String actdeparttime;
	private boolean valid;
	private String updatedby;
	private Date updateddate;
	private String updatedip;
	private boolean doctoradvice;
	private String remarks;

	public Appointmentservicedetails() {
	}

	public Appointmentservicedetails(int sno, Appointment appointment,
			Roommaster roommaster, Servicemaster servicemaster,
			Staffmaster staffmaster, String schappointtime,
			String schdeparttime, boolean valid, String updatedby,
			Date updateddate, String updatedip, boolean doctoradvice) {
		this.sno = sno;
		this.appointment = appointment;
		this.roommaster = roommaster;
		this.servicemaster = servicemaster;
		this.staffmaster = staffmaster;
		this.schappointtime = schappointtime;
		this.schdeparttime = schdeparttime;
		this.valid = valid;
		this.updatedby = updatedby;
		this.updateddate = updateddate;
		this.updatedip = updatedip;
		this.doctoradvice = doctoradvice;
	}

	public Appointmentservicedetails(int sno, Appointment appointment,
			Packagemaster packagemaster, Roommaster roommaster,
			Servicemaster servicemaster, Staffmaster staffmaster,
			Statusmaster statusmaster, Date schappointdate,
			String schappointtime, Date actstartdate, String actstarttime,
			Date schdepartdate, String schdeparttime, Date actdepartdate,
			String actdeparttime, boolean valid, String updatedby,
			Date updateddate, String updatedip, boolean doctoradvice,
			String remarks) {
		this.sno = sno;
		this.appointment = appointment;
		this.packagemaster = packagemaster;
		this.roommaster = roommaster;
		this.servicemaster = servicemaster;
		this.staffmaster = staffmaster;
		this.statusmaster = statusmaster;
		this.schappointdate = schappointdate;
		this.schappointtime = schappointtime;
		this.actstartdate = actstartdate;
		this.actstarttime = actstarttime;
		this.schdepartdate = schdepartdate;
		this.schdeparttime = schdeparttime;
		this.actdepartdate = actdepartdate;
		this.actdeparttime = actdeparttime;
		this.valid = valid;
		this.updatedby = updatedby;
		this.updateddate = updateddate;
		this.updatedip = updatedip;
		this.doctoradvice = doctoradvice;
		this.remarks = remarks;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "sno", unique = true, insertable = false, nullable = false)
	public int getSno() {
		return this.sno;
	}

	public void setSno(int sno) {
		this.sno = sno;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "appointmentid", nullable = false)
	public Appointment getAppointment() {
		return this.appointment;
	}

	public void setAppointment(Appointment appointment) {
		this.appointment = appointment;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "packageid")
	public Packagemaster getPackagemaster() {
		return this.packagemaster;
	}

	public void setPackagemaster(Packagemaster packagemaster) {
		this.packagemaster = packagemaster;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "roomid", nullable = false)
	public Roommaster getRoommaster() {
		return this.roommaster;
	}

	public void setRoommaster(Roommaster roommaster) {
		this.roommaster = roommaster;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "serviceid", nullable = false)
	public Servicemaster getServicemaster() {
		return this.servicemaster;
	}

	public void setServicemaster(Servicemaster servicemaster) {
		this.servicemaster = servicemaster;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "staffid", nullable = false)
	public Staffmaster getStaffmaster() {
		return this.staffmaster;
	}

	public void setStaffmaster(Staffmaster staffmaster) {
		this.staffmaster = staffmaster;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "statusid")
	public Statusmaster getStatusmaster() {
		return this.statusmaster;
	}

	public void setStatusmaster(Statusmaster statusmaster) {
		this.statusmaster = statusmaster;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "schappointdate", length = 13)
	public Date getSchappointdate() {
		return this.schappointdate;
	}

	public void setSchappointdate(Date schappointdate) {
		this.schappointdate = schappointdate;
	}

	@Column(name = "schappointtime", nullable = false, length = 10)
	public String getSchappointtime() {
		return this.schappointtime;
	}

	public void setSchappointtime(String schappointtime) {
		this.schappointtime = schappointtime;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "actstartdate", length = 13)
	public Date getActstartdate() {
		return this.actstartdate;
	}

	public void setActstartdate(Date actstartdate) {
		this.actstartdate = actstartdate;
	}

	@Column(name = "actstarttime", length = 10)
	public String getActstarttime() {
		return this.actstarttime;
	}

	public void setActstarttime(String actstarttime) {
		this.actstarttime = actstarttime;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "schdepartdate", length = 13)
	public Date getSchdepartdate() {
		return this.schdepartdate;
	}

	public void setSchdepartdate(Date schdepartdate) {
		this.schdepartdate = schdepartdate;
	}

	@Column(name = "schdeparttime", nullable = false, length = 10)
	public String getSchdeparttime() {
		return this.schdeparttime;
	}

	public void setSchdeparttime(String schdeparttime) {
		this.schdeparttime = schdeparttime;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "actdepartdate", length = 13)
	public Date getActdepartdate() {
		return this.actdepartdate;
	}

	public void setActdepartdate(Date actdepartdate) {
		this.actdepartdate = actdepartdate;
	}

	@Column(name = "actdeparttime", length = 10)
	public String getActdeparttime() {
		return this.actdeparttime;
	}

	public void setActdeparttime(String actdeparttime) {
		this.actdeparttime = actdeparttime;
	}

	@Column(name = "valid", nullable = false)
	public boolean isValid() {
		return this.valid;
	}

	public void setValid(boolean valid) {
		this.valid = valid;
	}

	@Column(name = "updatedby", nullable = false, length = 150)
	public String getUpdatedby() {
		return this.updatedby;
	}

	public void setUpdatedby(String updatedby) {
		this.updatedby = updatedby;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updateddate", nullable = false, length = 29)
	public Date getUpdateddate() {
		return this.updateddate;
	}

	public void setUpdateddate(Date updateddate) {
		this.updateddate = updateddate;
	}

	@Column(name = "updatedip", nullable = false, length = 150)
	public String getUpdatedip() {
		return this.updatedip;
	}

	public void setUpdatedip(String updatedip) {
		this.updatedip = updatedip;
	}

	@Column(name = "doctoradvice")
	public boolean isDoctoradvice() {
		return this.doctoradvice;
	}

	public void setDoctoradvice(boolean doctoradvice) {
		this.doctoradvice = doctoradvice;
	}

	@Column(name = "remarks")
	public String getRemarks() {
		return this.remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

}
