package com.leonia.wellness.entity;

// Generated 2 Jul, 2016 7:32:27 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.Generated;
import org.hibernate.annotations.GenerationTime;

/**
 * Corporatetypemaster generated by hbm2java
 */
@Entity
@Table(name = "corporatetypemaster")
public class Corporatetypemaster implements java.io.Serializable {

	private int corporatetypeid;
	private int sno;
	private String corporatetype;
	private boolean valid;
	private String updatedby;
	private Date updateddate;
	private String updatedip;
	private Set<Corporatemaster> corporatemasters = new HashSet<Corporatemaster>(
			0);

	public Corporatetypemaster() {
	}

	public Corporatetypemaster(int corporatetypeid, int sno,
			String corporatetype, boolean valid, String updatedby,
			Date updateddate, String updatedip) {
		this.corporatetypeid = corporatetypeid;
		this.sno = sno;
		this.corporatetype = corporatetype;
		this.valid = valid;
		this.updatedby = updatedby;
		this.updateddate = updateddate;
		this.updatedip = updatedip;
	}

	public Corporatetypemaster(int corporatetypeid, int sno,
			String corporatetype, boolean valid, String updatedby,
			Date updateddate, String updatedip,
			Set<Corporatemaster> corporatemasters) {
		this.corporatetypeid = corporatetypeid;
		this.sno = sno;
		this.corporatetype = corporatetype;
		this.valid = valid;
		this.updatedby = updatedby;
		this.updateddate = updateddate;
		this.updatedip = updatedip;
		this.corporatemasters = corporatemasters;
	}

	@Id
	@Column(name = "corporatetypeid", unique = true, nullable = false)
	public int getCorporatetypeid() {
		return this.corporatetypeid;
	}

	public void setCorporatetypeid(int corporatetypeid) {
		this.corporatetypeid = corporatetypeid;
	}

	@Generated(GenerationTime.INSERT)
	@Column(name = "sno", insertable = false, nullable = false)
	public int getSno() {
		return this.sno;
	}

	public void setSno(int sno) {
		this.sno = sno;
	}

	@Column(name = "corporatetype", nullable = false, length = 200)
	public String getCorporatetype() {
		return this.corporatetype;
	}

	public void setCorporatetype(String corporatetype) {
		this.corporatetype = corporatetype;
	}

	@Column(name = "valid", nullable = false)
	public boolean isValid() {
		return this.valid;
	}

	public void setValid(boolean valid) {
		this.valid = valid;
	}

	@Column(name = "updatedby", nullable = false, length = 150)
	public String getUpdatedby() {
		return this.updatedby;
	}

	public void setUpdatedby(String updatedby) {
		this.updatedby = updatedby;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updateddate", nullable = false, length = 29)
	public Date getUpdateddate() {
		return this.updateddate;
	}

	public void setUpdateddate(Date updateddate) {
		this.updateddate = updateddate;
	}

	@Column(name = "updatedip", nullable = false, length = 150)
	public String getUpdatedip() {
		return this.updatedip;
	}

	public void setUpdatedip(String updatedip) {
		this.updatedip = updatedip;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "corporatetypemaster")
	public Set<Corporatemaster> getCorporatemasters() {
		return this.corporatemasters;
	}

	public void setCorporatemasters(Set<Corporatemaster> corporatemasters) {
		this.corporatemasters = corporatemasters;
	}

}
