package com.leonia.wellness.entity;

// Generated 2 Jul, 2016 7:32:27 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.Generated;
import org.hibernate.annotations.GenerationTime;

/**
 * Countrymaster generated by hbm2java
 */
@Entity
@Table(name = "countrymaster")
public class Countrymaster implements java.io.Serializable {

	private int countryid;
	private int sno;
	private String countryname;
	private boolean valid;
	private String updatedby;
	private Date updateddate;
	private String updatedip;
	private Set<Guestmaster> guestmasters = new HashSet<Guestmaster>(0);
	private Set<Staffmaster> staffmasters = new HashSet<Staffmaster>(0);
	private Set<Statemaster> statemasters = new HashSet<Statemaster>(0);

	public Countrymaster() {
	}

	public Countrymaster(int countryid, int sno, String countryname,
			boolean valid, String updatedby, Date updateddate, String updatedip) {
		this.countryid = countryid;
		this.sno = sno;
		this.countryname = countryname;
		this.valid = valid;
		this.updatedby = updatedby;
		this.updateddate = updateddate;
		this.updatedip = updatedip;
	}

	public Countrymaster(int countryid, int sno, String countryname,
			boolean valid, String updatedby, Date updateddate,
			String updatedip, Set<Guestmaster> guestmasters,
			Set<Staffmaster> staffmasters, Set<Statemaster> statemasters) {
		this.countryid = countryid;
		this.sno = sno;
		this.countryname = countryname;
		this.valid = valid;
		this.updatedby = updatedby;
		this.updateddate = updateddate;
		this.updatedip = updatedip;
		this.guestmasters = guestmasters;
		this.staffmasters = staffmasters;
		this.statemasters = statemasters;
	}

	@Id
	@Column(name = "countryid", unique = true, nullable = false)
	public int getCountryid() {
		return this.countryid;
	}

	public void setCountryid(int countryid) {
		this.countryid = countryid;
	}

	@Generated(GenerationTime.INSERT)
	@Column(name = "sno", insertable = false, nullable = false)
	public int getSno() {
		return this.sno;
	}

	public void setSno(int sno) {
		this.sno = sno;
	}

	@Column(name = "countryname", nullable = false, length = 100)
	public String getCountryname() {
		return this.countryname;
	}

	public void setCountryname(String countryname) {
		this.countryname = countryname;
	}

	@Column(name = "valid", nullable = false)
	public boolean isValid() {
		return this.valid;
	}

	public void setValid(boolean valid) {
		this.valid = valid;
	}

	@Column(name = "updatedby", nullable = false, length = 150)
	public String getUpdatedby() {
		return this.updatedby;
	}

	public void setUpdatedby(String updatedby) {
		this.updatedby = updatedby;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updateddate", nullable = false, length = 29)
	public Date getUpdateddate() {
		return this.updateddate;
	}

	public void setUpdateddate(Date updateddate) {
		this.updateddate = updateddate;
	}

	@Column(name = "updatedip", nullable = false, length = 150)
	public String getUpdatedip() {
		return this.updatedip;
	}

	public void setUpdatedip(String updatedip) {
		this.updatedip = updatedip;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "countrymaster")
	public Set<Guestmaster> getGuestmasters() {
		return this.guestmasters;
	}

	public void setGuestmasters(Set<Guestmaster> guestmasters) {
		this.guestmasters = guestmasters;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "countrymaster")
	public Set<Staffmaster> getStaffmasters() {
		return this.staffmasters;
	}

	public void setStaffmasters(Set<Staffmaster> staffmasters) {
		this.staffmasters = staffmasters;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "countrymaster")
	public Set<Statemaster> getStatemasters() {
		return this.statemasters;
	}

	public void setStatemasters(Set<Statemaster> statemasters) {
		this.statemasters = statemasters;
	}

}
