package com.leonia.wellness.entity;
// Generated Aug 20, 2016 2:52:14 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.Generated;
import org.hibernate.annotations.GenerationTime;

/**
 * Departmentmaster generated by hbm2java
 */
@Entity
@Table(name = "departmentmaster")
public class Departmentmaster implements java.io.Serializable {

	private int departmentid;
	private int sno;
	private String departmentname;
	private String description;
	private boolean valid;
	private String updatedby;
	private Date updateddate;
	private String updatedip;
	private Set<Questionmaster> questionmasters = new HashSet<Questionmaster>(0);
	private Set<Staffmaster> staffmasters = new HashSet<Staffmaster>(0);
	private Set<Ticketmaster> ticketmasters = new HashSet<Ticketmaster>(0);

	public Departmentmaster() {
	}

	public Departmentmaster(int departmentid, int sno, boolean valid, String updatedby, Date updateddate,
			String updatedip) {
		this.departmentid = departmentid;
		this.sno = sno;
		this.valid = valid;
		this.updatedby = updatedby;
		this.updateddate = updateddate;
		this.updatedip = updatedip;
	}

	public Departmentmaster(int departmentid, int sno, String departmentname, String description, boolean valid,
			String updatedby, Date updateddate, String updatedip, Set<Questionmaster> questionmasters,
			Set<Staffmaster> staffmasters, Set<Ticketmaster> ticketmasters) {
		this.departmentid = departmentid;
		this.sno = sno;
		this.departmentname = departmentname;
		this.description = description;
		this.valid = valid;
		this.updatedby = updatedby;
		this.updateddate = updateddate;
		this.updatedip = updatedip;
		this.questionmasters = questionmasters;
		this.staffmasters = staffmasters;
		this.ticketmasters = ticketmasters;
	}

	@Id

	@Column(name = "departmentid", unique = true, nullable = false)
	public int getDepartmentid() {
		return this.departmentid;
	}

	public void setDepartmentid(int departmentid) {
		this.departmentid = departmentid;
	}

	@Generated(GenerationTime.INSERT)
	@Column(name = "sno", insertable = false, nullable = false)
	public int getSno() {
		return this.sno;
	}

	public void setSno(int sno) {
		this.sno = sno;
	}

	@Column(name = "departmentname", length = 200)
	public String getDepartmentname() {
		return this.departmentname;
	}

	public void setDepartmentname(String departmentname) {
		this.departmentname = departmentname;
	}

	@Column(name = "description")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "valid", nullable = false)
	public boolean isValid() {
		return this.valid;
	}

	public void setValid(boolean valid) {
		this.valid = valid;
	}

	@Column(name = "updatedby", nullable = false, length = 150)
	public String getUpdatedby() {
		return this.updatedby;
	}

	public void setUpdatedby(String updatedby) {
		this.updatedby = updatedby;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updateddate", nullable = false, length = 29)
	public Date getUpdateddate() {
		return this.updateddate;
	}

	public void setUpdateddate(Date updateddate) {
		this.updateddate = updateddate;
	}

	@Column(name = "updatedip", nullable = false, length = 150)
	public String getUpdatedip() {
		return this.updatedip;
	}

	public void setUpdatedip(String updatedip) {
		this.updatedip = updatedip;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "departmentmaster")
	public Set<Questionmaster> getQuestionmasters() {
		return this.questionmasters;
	}

	public void setQuestionmasters(Set<Questionmaster> questionmasters) {
		this.questionmasters = questionmasters;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "departmentmaster")
	public Set<Staffmaster> getStaffmasters() {
		return this.staffmasters;
	}

	public void setStaffmasters(Set<Staffmaster> staffmasters) {
		this.staffmasters = staffmasters;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "departmentmaster")
	public Set<Ticketmaster> getTicketmasters() {
		return this.ticketmasters;
	}

	public void setTicketmasters(Set<Ticketmaster> ticketmasters) {
		this.ticketmasters = ticketmasters;
	}

}
