package com.leonia.wellness.entity;

// Generated 9 Aug, 2016 6:02:31 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.Generated;
import org.hibernate.annotations.GenerationTime;

/**
 * Discountmaster generated by hbm2java
 */
@Entity
@Table(name = "discountmaster")
public class Discountmaster implements java.io.Serializable {

	private int discountid;
	private Billmaster billmaster;
	private int sno;
	private String discounttype;
	private BigDecimal discount;
	private String discountreason;
	private boolean valid;
	private String updatedby;
	private Date updateddate;
	private String updatedip;
	private Set<Billdetails> billdetailses = new HashSet<Billdetails>(0);

	public Discountmaster() {
	}

	public Discountmaster(int discountid, int sno, String discounttype,
			BigDecimal discount, String discountreason, boolean valid,
			String updatedby, Date updateddate, String updatedip) {
		this.discountid = discountid;
		this.sno = sno;
		this.discounttype = discounttype;
		this.discount = discount;
		this.discountreason = discountreason;
		this.valid = valid;
		this.updatedby = updatedby;
		this.updateddate = updateddate;
		this.updatedip = updatedip;
	}

	public Discountmaster(int discountid, Billmaster billmaster, int sno,
			String discounttype, BigDecimal discount, String discountreason,
			boolean valid, String updatedby, Date updateddate,
			String updatedip, Set<Billdetails> billdetailses) {
		this.discountid = discountid;
		this.billmaster = billmaster;
		this.sno = sno;
		this.discounttype = discounttype;
		this.discount = discount;
		this.discountreason = discountreason;
		this.valid = valid;
		this.updatedby = updatedby;
		this.updateddate = updateddate;
		this.updatedip = updatedip;
		this.billdetailses = billdetailses;
	}

	@Id
	@Column(name = "discountid", unique = true, nullable = false)
	public int getDiscountid() {
		return this.discountid;
	}

	public void setDiscountid(int discountid) {
		this.discountid = discountid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "billno")
	public Billmaster getBillmaster() {
		return this.billmaster;
	}

	public void setBillmaster(Billmaster billmaster) {
		this.billmaster = billmaster;
	}

	@Generated(GenerationTime.INSERT)
	@Column(name = "sno", insertable = false, nullable = false)
	public int getSno() {
		return this.sno;
	}

	public void setSno(int sno) {
		this.sno = sno;
	}

	@Column(name = "discounttype", nullable = false, length = 150)
	public String getDiscounttype() {
		return this.discounttype;
	}

	public void setDiscounttype(String discounttype) {
		this.discounttype = discounttype;
	}

	@Column(name = "discount", nullable = false, precision = 15)
	public BigDecimal getDiscount() {
		return this.discount;
	}

	public void setDiscount(BigDecimal discount) {
		this.discount = discount;
	}

	@Column(name = "discountreason", nullable = false)
	public String getDiscountreason() {
		return this.discountreason;
	}

	public void setDiscountreason(String discountreason) {
		this.discountreason = discountreason;
	}

	@Column(name = "valid", nullable = false)
	public boolean isValid() {
		return this.valid;
	}

	public void setValid(boolean valid) {
		this.valid = valid;
	}

	@Column(name = "updatedby", nullable = false, length = 150)
	public String getUpdatedby() {
		return this.updatedby;
	}

	public void setUpdatedby(String updatedby) {
		this.updatedby = updatedby;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updateddate", nullable = false, length = 29)
	public Date getUpdateddate() {
		return this.updateddate;
	}

	public void setUpdateddate(Date updateddate) {
		this.updateddate = updateddate;
	}

	@Column(name = "updatedip", nullable = false, length = 150)
	public String getUpdatedip() {
		return this.updatedip;
	}

	public void setUpdatedip(String updatedip) {
		this.updatedip = updatedip;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "discountmaster")
	public Set<Billdetails> getBilldetailses() {
		return this.billdetailses;
	}

	public void setBilldetailses(Set<Billdetails> billdetailses) {
		this.billdetailses = billdetailses;
	}

}
