package com.leonia.wellness.entity;

// Generated 8 Aug, 2016 12:23:20 PM by Hibernate Tools 4.3.1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Feedbackdetails generated by hbm2java
 */
@Entity
@Table(name = "feedbackdetails")
public class Feedbackdetails implements java.io.Serializable {

	private int sno;
	private Feedbackformmaster feedbackformmaster;
	private Responsemaster responsemaster;
	private int questionid;
	private boolean valid;
	private String updatedby;
	private Date updateddate;
	private String updatedip;

	public Feedbackdetails() {
	}

	public Feedbackdetails(int sno, Feedbackformmaster feedbackformmaster,
			Responsemaster responsemaster, int questionid, boolean valid,
			String updatedby, Date updateddate, String updatedip) {
		this.sno = sno;
		this.feedbackformmaster = feedbackformmaster;
		this.responsemaster = responsemaster;
		this.questionid = questionid;
		this.valid = valid;
		this.updatedby = updatedby;
		this.updateddate = updateddate;
		this.updatedip = updatedip;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "sno", unique = true, insertable = false, nullable = false)
	public int getSno() {
		return this.sno;
	}

	public void setSno(int sno) {
		this.sno = sno;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "feedbackformid", nullable = false)
	public Feedbackformmaster getFeedbackformmaster() {
		return this.feedbackformmaster;
	}

	public void setFeedbackformmaster(Feedbackformmaster feedbackformmaster) {
		this.feedbackformmaster = feedbackformmaster;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "responseid", nullable = false)
	public Responsemaster getResponsemaster() {
		return this.responsemaster;
	}

	public void setResponsemaster(Responsemaster responsemaster) {
		this.responsemaster = responsemaster;
	}

	@Column(name = "questionid", nullable = false)
	public int getQuestionid() {
		return this.questionid;
	}

	public void setQuestionid(int questionid) {
		this.questionid = questionid;
	}

	@Column(name = "valid", nullable = false)
	public boolean isValid() {
		return this.valid;
	}

	public void setValid(boolean valid) {
		this.valid = valid;
	}

	@Column(name = "updatedby", nullable = false, length = 150)
	public String getUpdatedby() {
		return this.updatedby;
	}

	public void setUpdatedby(String updatedby) {
		this.updatedby = updatedby;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updateddate", nullable = false, length = 29)
	public Date getUpdateddate() {
		return this.updateddate;
	}

	public void setUpdateddate(Date updateddate) {
		this.updateddate = updateddate;
	}

	@Column(name = "updatedip", nullable = false, length = 150)
	public String getUpdatedip() {
		return this.updatedip;
	}

	public void setUpdatedip(String updatedip) {
		this.updatedip = updatedip;
	}

}
