package com.leonia.wellness.entity;

// Generated 3 Aug, 2016 11:27:47 AM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.Generated;
import org.hibernate.annotations.GenerationTime;

/**
 * Packageratemaster generated by hbm2java
 */
@Entity
@Table(name = "packageratemaster")
public class Packageratemaster implements java.io.Serializable {

	private int packagerateid;
	private Packagemaster packagemaster;
	private Taxstructuremaster taxstructuremaster;
	private int sno;
	private BigDecimal packagecost;
	private int taxstructureid;
	private Date applicabledate;
	private boolean valid;
	private String updatedby;
	private Date updateddate;
	private String updatedip;

	public Packageratemaster() {
	}

	public Packageratemaster(int packagerateid, Packagemaster packagemaster,
			Taxstructuremaster taxstructuremaster, int sno,
			BigDecimal packagecost, int taxstructureid, Date applicabledate,
			boolean valid, String updatedby, Date updateddate, String updatedip) {
		this.packagerateid = packagerateid;
		this.packagemaster = packagemaster;
		this.taxstructuremaster = taxstructuremaster;
		this.sno = sno;
		this.packagecost = packagecost;
		this.taxstructureid = taxstructureid;
		this.applicabledate = applicabledate;
		this.valid = valid;
		this.updatedby = updatedby;
		this.updateddate = updateddate;
		this.updatedip = updatedip;
	}

	@Id
	@Column(name = "packagerateid", unique = true, nullable = false)
	public int getPackagerateid() {
		return this.packagerateid;
	}

	public void setPackagerateid(int packagerateid) {
		this.packagerateid = packagerateid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "packageid", nullable = false)
	public Packagemaster getPackagemaster() {
		return this.packagemaster;
	}

	public void setPackagemaster(Packagemaster packagemaster) {
		this.packagemaster = packagemaster;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "taxstructurecode", nullable = false)
	public Taxstructuremaster getTaxstructuremaster() {
		return this.taxstructuremaster;
	}

	public void setTaxstructuremaster(Taxstructuremaster taxstructuremaster) {
		this.taxstructuremaster = taxstructuremaster;
	}

	@Generated(GenerationTime.INSERT)
	@Column(name = "sno", insertable = false, nullable = false)
	public int getSno() {
		return this.sno;
	}

	public void setSno(int sno) {
		this.sno = sno;
	}

	@Column(name = "packagecost", nullable = false, precision = 15)
	public BigDecimal getPackagecost() {
		return this.packagecost;
	}

	public void setPackagecost(BigDecimal packagecost) {
		this.packagecost = packagecost;
	}

	@Column(name = "taxstructureid", nullable = false)
	public int getTaxstructureid() {
		return this.taxstructureid;
	}

	public void setTaxstructureid(int taxstructureid) {
		this.taxstructureid = taxstructureid;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "applicabledate", nullable = false, length = 13)
	public Date getApplicabledate() {
		return this.applicabledate;
	}

	public void setApplicabledate(Date applicabledate) {
		this.applicabledate = applicabledate;
	}

	@Column(name = "valid", nullable = false)
	public boolean isValid() {
		return this.valid;
	}

	public void setValid(boolean valid) {
		this.valid = valid;
	}

	@Column(name = "updatedby", nullable = false, length = 150)
	public String getUpdatedby() {
		return this.updatedby;
	}

	public void setUpdatedby(String updatedby) {
		this.updatedby = updatedby;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updateddate", nullable = false, length = 29)
	public Date getUpdateddate() {
		return this.updateddate;
	}

	public void setUpdateddate(Date updateddate) {
		this.updateddate = updateddate;
	}

	@Column(name = "updatedip", nullable = false, length = 150)
	public String getUpdatedip() {
		return this.updatedip;
	}

	public void setUpdatedip(String updatedip) {
		this.updatedip = updatedip;
	}

}
