package com.leonia.wellness.entity;

// Generated 9 Aug, 2016 6:02:31 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.Generated;
import org.hibernate.annotations.GenerationTime;

/**
 * Packagemaster generated by hbm2java
 */
@Entity
@Table(name = "packagemaster")
public class Packagemaster implements java.io.Serializable {

	private int packageid;
	private int sno;
	private String packagename;
	private boolean valid;
	private String updatedby;
	private Date updateddate;
	private String updatedip;
	private Set<Packageratemaster> packageratemasters = new HashSet<Packageratemaster>(
			0);
	private Set<Packageservices> packageserviceses = new HashSet<Packageservices>(
			0);
	private Set<Billdetails> billdetailses = new HashSet<Billdetails>(0);
	private Set<Appointmentstockconsumption> appointmentstockconsumptions = new HashSet<Appointmentstockconsumption>(
			0);
	private Set<Guesthistoryservices> guesthistoryserviceses = new HashSet<Guesthistoryservices>(
			0);
	private Set<Appointmentservicedetails> appointmentservicedetailses = new HashSet<Appointmentservicedetails>(
			0);

	public Packagemaster() {
	}

	public Packagemaster(int packageid, int sno, String packagename,
			boolean valid, String updatedby, Date updateddate, String updatedip) {
		this.packageid = packageid;
		this.sno = sno;
		this.packagename = packagename;
		this.valid = valid;
		this.updatedby = updatedby;
		this.updateddate = updateddate;
		this.updatedip = updatedip;
	}

	public Packagemaster(int packageid, int sno, String packagename,
			boolean valid, String updatedby, Date updateddate,
			String updatedip, Set<Packageratemaster> packageratemasters,
			Set<Packageservices> packageserviceses,
			Set<Billdetails> billdetailses,
			Set<Appointmentstockconsumption> appointmentstockconsumptions,
			Set<Guesthistoryservices> guesthistoryserviceses,
			Set<Appointmentservicedetails> appointmentservicedetailses) {
		this.packageid = packageid;
		this.sno = sno;
		this.packagename = packagename;
		this.valid = valid;
		this.updatedby = updatedby;
		this.updateddate = updateddate;
		this.updatedip = updatedip;
		this.packageratemasters = packageratemasters;
		this.packageserviceses = packageserviceses;
		this.billdetailses = billdetailses;
		this.appointmentstockconsumptions = appointmentstockconsumptions;
		this.guesthistoryserviceses = guesthistoryserviceses;
		this.appointmentservicedetailses = appointmentservicedetailses;
	}

	@Id
	@Column(name = "packageid", unique = true, nullable = false)
	public int getPackageid() {
		return this.packageid;
	}

	public void setPackageid(int packageid) {
		this.packageid = packageid;
	}

	@Generated(GenerationTime.INSERT)
	@Column(name = "sno", insertable = false, nullable = false)
	public int getSno() {
		return this.sno;
	}

	public void setSno(int sno) {
		this.sno = sno;
	}

	@Column(name = "packagename", nullable = false, length = 200)
	public String getPackagename() {
		return this.packagename;
	}

	public void setPackagename(String packagename) {
		this.packagename = packagename;
	}

	@Column(name = "valid", nullable = false)
	public boolean isValid() {
		return this.valid;
	}

	public void setValid(boolean valid) {
		this.valid = valid;
	}

	@Column(name = "updatedby", nullable = false, length = 150)
	public String getUpdatedby() {
		return this.updatedby;
	}

	public void setUpdatedby(String updatedby) {
		this.updatedby = updatedby;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updateddate", nullable = false, length = 29)
	public Date getUpdateddate() {
		return this.updateddate;
	}

	public void setUpdateddate(Date updateddate) {
		this.updateddate = updateddate;
	}

	@Column(name = "updatedip", nullable = false, length = 150)
	public String getUpdatedip() {
		return this.updatedip;
	}

	public void setUpdatedip(String updatedip) {
		this.updatedip = updatedip;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "packagemaster")
	public Set<Packageratemaster> getPackageratemasters() {
		return this.packageratemasters;
	}

	public void setPackageratemasters(Set<Packageratemaster> packageratemasters) {
		this.packageratemasters = packageratemasters;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "packagemaster")
	public Set<Packageservices> getPackageserviceses() {
		return this.packageserviceses;
	}

	public void setPackageserviceses(Set<Packageservices> packageserviceses) {
		this.packageserviceses = packageserviceses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "packagemaster")
	public Set<Billdetails> getBilldetailses() {
		return this.billdetailses;
	}

	public void setBilldetailses(Set<Billdetails> billdetailses) {
		this.billdetailses = billdetailses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "packagemaster")
	public Set<Appointmentstockconsumption> getAppointmentstockconsumptions() {
		return this.appointmentstockconsumptions;
	}

	public void setAppointmentstockconsumptions(
			Set<Appointmentstockconsumption> appointmentstockconsumptions) {
		this.appointmentstockconsumptions = appointmentstockconsumptions;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "packagemaster")
	public Set<Guesthistoryservices> getGuesthistoryserviceses() {
		return this.guesthistoryserviceses;
	}

	public void setGuesthistoryserviceses(
			Set<Guesthistoryservices> guesthistoryserviceses) {
		this.guesthistoryserviceses = guesthistoryserviceses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "packagemaster")
	public Set<Appointmentservicedetails> getAppointmentservicedetailses() {
		return this.appointmentservicedetailses;
	}

	public void setAppointmentservicedetailses(
			Set<Appointmentservicedetails> appointmentservicedetailses) {
		this.appointmentservicedetailses = appointmentservicedetailses;
	}

}
