package com.leonia.wellness.entity;
// Generated Aug 20, 2016 4:14:06 PM by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.Generated;
import org.hibernate.annotations.GenerationTime;

/**
 * Productsales generated by hbm2java
 */
@Entity
@Table(name = "productsales")
public class Productsales implements java.io.Serializable {

	private int productsalesid;
	private Billmaster billmaster;
	private Stockmaster stockmaster;
	private int sno;
	private BigDecimal unitprice;
	private int quantity;
	private BigDecimal totalamount;
	private boolean valid;
	private String updatedby;
	private Date updateddate;
	private String updatedip;

	public Productsales() {
	}

	public Productsales(int productsalesid, Stockmaster stockmaster, int sno, BigDecimal unitprice, int quantity,
			BigDecimal totalamount, boolean valid, String updatedby, Date updateddate, String updatedip) {
		this.productsalesid = productsalesid;
		this.stockmaster = stockmaster;
		this.sno = sno;
		this.unitprice = unitprice;
		this.quantity = quantity;
		this.totalamount = totalamount;
		this.valid = valid;
		this.updatedby = updatedby;
		this.updateddate = updateddate;
		this.updatedip = updatedip;
	}

	public Productsales(int productsalesid, Billmaster billmaster, Stockmaster stockmaster, int sno,
			BigDecimal unitprice, int quantity, BigDecimal totalamount, boolean valid, String updatedby,
			Date updateddate, String updatedip) {
		this.productsalesid = productsalesid;
		this.billmaster = billmaster;
		this.stockmaster = stockmaster;
		this.sno = sno;
		this.unitprice = unitprice;
		this.quantity = quantity;
		this.totalamount = totalamount;
		this.valid = valid;
		this.updatedby = updatedby;
		this.updateddate = updateddate;
		this.updatedip = updatedip;
	}

	@Id

	@Column(name = "productsalesid", unique = true, nullable = false)
	public int getProductsalesid() {
		return this.productsalesid;
	}

	public void setProductsalesid(int productsalesid) {
		this.productsalesid = productsalesid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "billno")
	public Billmaster getBillmaster() {
		return this.billmaster;
	}

	public void setBillmaster(Billmaster billmaster) {
		this.billmaster = billmaster;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "stockid", nullable = false)
	public Stockmaster getStockmaster() {
		return this.stockmaster;
	}

	public void setStockmaster(Stockmaster stockmaster) {
		this.stockmaster = stockmaster;
	}

	@Generated(GenerationTime.INSERT)
	@Column(name = "sno", insertable = false, nullable = false)
	public int getSno() {
		return this.sno;
	}

	public void setSno(int sno) {
		this.sno = sno;
	}

	@Column(name = "unitprice", nullable = false, precision = 15)
	public BigDecimal getUnitprice() {
		return this.unitprice;
	}

	public void setUnitprice(BigDecimal unitprice) {
		this.unitprice = unitprice;
	}

	@Column(name = "quantity", nullable = false)
	public int getQuantity() {
		return this.quantity;
	}

	public void setQuantity(int quantity) {
		this.quantity = quantity;
	}

	@Column(name = "totalamount", nullable = false, precision = 15)
	public BigDecimal getTotalamount() {
		return this.totalamount;
	}

	public void setTotalamount(BigDecimal totalamount) {
		this.totalamount = totalamount;
	}

	@Column(name = "valid", nullable = false)
	public boolean isValid() {
		return this.valid;
	}

	public void setValid(boolean valid) {
		this.valid = valid;
	}

	@Column(name = "updatedby", nullable = false, length = 150)
	public String getUpdatedby() {
		return this.updatedby;
	}

	public void setUpdatedby(String updatedby) {
		this.updatedby = updatedby;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updateddate", nullable = false, length = 29)
	public Date getUpdateddate() {
		return this.updateddate;
	}

	public void setUpdateddate(Date updateddate) {
		this.updateddate = updateddate;
	}

	@Column(name = "updatedip", nullable = false, length = 150)
	public String getUpdatedip() {
		return this.updatedip;
	}

	public void setUpdatedip(String updatedip) {
		this.updatedip = updatedip;
	}

}
