package com.leonia.wellness.entity;

// Generated 20 Jul, 2016 3:39:07 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.Generated;
import org.hibernate.annotations.GenerationTime;

/**
 * Productratemaster generated by hbm2java
 */
@Entity
@Table(name = "productratemaster")
public class Productratemaster implements java.io.Serializable {

	private int productrateid;
	private Stockmaster stockmaster;
	private Taxstructuremaster taxstructuremaster;
	private int sno;
	private BigDecimal productcost;
	private int taxstructureid;
	private Date applicabledate;
	private boolean valid;
	private String updatedby;
	private Date updateddate;
	private String updatedip;

	public Productratemaster() {
	}

	public Productratemaster(int productrateid, Stockmaster stockmaster,
			Taxstructuremaster taxstructuremaster, int sno,
			BigDecimal productcost, int taxstructureid, Date applicabledate,
			boolean valid, String updatedby, Date updateddate, String updatedip) {
		this.productrateid = productrateid;
		this.stockmaster = stockmaster;
		this.taxstructuremaster = taxstructuremaster;
		this.sno = sno;
		this.productcost = productcost;
		this.taxstructureid = taxstructureid;
		this.applicabledate = applicabledate;
		this.valid = valid;
		this.updatedby = updatedby;
		this.updateddate = updateddate;
		this.updatedip = updatedip;
	}

	@Id
	@Column(name = "productrateid", unique = true, nullable = false)
	public int getProductrateid() {
		return this.productrateid;
	}

	public void setProductrateid(int productrateid) {
		this.productrateid = productrateid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "productid", nullable = false)
	public Stockmaster getStockmaster() {
		return this.stockmaster;
	}

	public void setStockmaster(Stockmaster stockmaster) {
		this.stockmaster = stockmaster;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "taxstructurecode", nullable = false)
	public Taxstructuremaster getTaxstructuremaster() {
		return this.taxstructuremaster;
	}

	public void setTaxstructuremaster(Taxstructuremaster taxstructuremaster) {
		this.taxstructuremaster = taxstructuremaster;
	}

	@Generated(GenerationTime.INSERT)
	@Column(name = "sno", insertable = false, nullable = false)
	public int getSno() {
		return this.sno;
	}

	public void setSno(int sno) {
		this.sno = sno;
	}

	@Column(name = "productcost", nullable = false, precision = 15)
	public BigDecimal getProductcost() {
		return this.productcost;
	}

	public void setProductcost(BigDecimal productcost) {
		this.productcost = productcost;
	}

	@Column(name = "taxstructureid", nullable = false)
	public int getTaxstructureid() {
		return this.taxstructureid;
	}

	public void setTaxstructureid(int taxstructureid) {
		this.taxstructureid = taxstructureid;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "applicabledate", nullable = false, length = 13)
	public Date getApplicabledate() {
		return this.applicabledate;
	}

	public void setApplicabledate(Date applicabledate) {
		this.applicabledate = applicabledate;
	}

	@Column(name = "valid", nullable = false)
	public boolean isValid() {
		return this.valid;
	}

	public void setValid(boolean valid) {
		this.valid = valid;
	}

	@Column(name = "updatedby", nullable = false, length = 150)
	public String getUpdatedby() {
		return this.updatedby;
	}

	public void setUpdatedby(String updatedby) {
		this.updatedby = updatedby;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updateddate", nullable = false, length = 29)
	public Date getUpdateddate() {
		return this.updateddate;
	}

	public void setUpdateddate(Date updateddate) {
		this.updateddate = updateddate;
	}

	@Column(name = "updatedip", nullable = false, length = 150)
	public String getUpdatedip() {
		return this.updatedip;
	}

	public void setUpdatedip(String updatedip) {
		this.updatedip = updatedip;
	}

}
