package com.leonia.wellness.entity;

// Generated 8 Aug, 2016 2:04:11 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.Generated;
import org.hibernate.annotations.GenerationTime;

/**
 * Reasonmaster generated by hbm2java
 */
@Entity
@Table(name = "reasonmaster")
public class Reasonmaster implements java.io.Serializable {

	private int reasonid;
	private int sno;
	private String description;
	private boolean valid;
	private String updatedby;
	private Date updateddate;
	private String updatedip;
	private Set<Reasondetails> reasondetailses = new HashSet<Reasondetails>(0);

	public Reasonmaster() {
	}

	public Reasonmaster(int reasonid, int sno, String description,
			boolean valid, String updatedby, Date updateddate, String updatedip) {
		this.reasonid = reasonid;
		this.sno = sno;
		this.description = description;
		this.valid = valid;
		this.updatedby = updatedby;
		this.updateddate = updateddate;
		this.updatedip = updatedip;
	}

	public Reasonmaster(int reasonid, int sno, String description,
			boolean valid, String updatedby, Date updateddate,
			String updatedip, Set<Reasondetails> reasondetailses) {
		this.reasonid = reasonid;
		this.sno = sno;
		this.description = description;
		this.valid = valid;
		this.updatedby = updatedby;
		this.updateddate = updateddate;
		this.updatedip = updatedip;
		this.reasondetailses = reasondetailses;
	}

	@Id
	@Column(name = "reasonid", unique = true, nullable = false)
	public int getReasonid() {
		return this.reasonid;
	}

	public void setReasonid(int reasonid) {
		this.reasonid = reasonid;
	}

	@Generated(GenerationTime.INSERT)
	@Column(name = "sno", insertable = false, nullable = false)
	public int getSno() {
		return this.sno;
	}

	public void setSno(int sno) {
		this.sno = sno;
	}

	@Column(name = "description", nullable = false, length = 250)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "valid", nullable = false)
	public boolean isValid() {
		return this.valid;
	}

	public void setValid(boolean valid) {
		this.valid = valid;
	}

	@Column(name = "updatedby", nullable = false, length = 150)
	public String getUpdatedby() {
		return this.updatedby;
	}

	public void setUpdatedby(String updatedby) {
		this.updatedby = updatedby;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updateddate", nullable = false, length = 29)
	public Date getUpdateddate() {
		return this.updateddate;
	}

	public void setUpdateddate(Date updateddate) {
		this.updateddate = updateddate;
	}

	@Column(name = "updatedip", nullable = false, length = 150)
	public String getUpdatedip() {
		return this.updatedip;
	}

	public void setUpdatedip(String updatedip) {
		this.updatedip = updatedip;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "reasonmaster")
	public Set<Reasondetails> getReasondetailses() {
		return this.reasondetailses;
	}

	public void setReasondetailses(Set<Reasondetails> reasondetailses) {
		this.reasondetailses = reasondetailses;
	}

}
