package com.leonia.wellness.entity;

// Generated 8 Aug, 2016 2:04:11 PM by Hibernate Tools 4.3.1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Reasondetails generated by hbm2java
 */
@Entity
@Table(name = "reasondetails")
public class Reasondetails implements java.io.Serializable {

	private int sno;
	private Reasonmaster reasonmaster;
	private int reasondetailsid;
	private String reasondescription;
	private boolean valid;
	private String updatedby;
	private Date updateddate;
	private String updatedip;

	public Reasondetails() {
	}

	public Reasondetails(int sno, Reasonmaster reasonmaster,
			int reasondetailsid, String reasondescription, boolean valid,
			String updatedby, Date updateddate, String updatedip) {
		this.sno = sno;
		this.reasonmaster = reasonmaster;
		this.reasondetailsid = reasondetailsid;
		this.reasondescription = reasondescription;
		this.valid = valid;
		this.updatedby = updatedby;
		this.updateddate = updateddate;
		this.updatedip = updatedip;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "sno", unique = true, insertable = false, nullable = false)
	public int getSno() {
		return this.sno;
	}

	public void setSno(int sno) {
		this.sno = sno;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "reasonid", nullable = false)
	public Reasonmaster getReasonmaster() {
		return this.reasonmaster;
	}

	public void setReasonmaster(Reasonmaster reasonmaster) {
		this.reasonmaster = reasonmaster;
	}

	@Column(name = "reasondetailsid", nullable = false)
	public int getReasondetailsid() {
		return this.reasondetailsid;
	}

	public void setReasondetailsid(int reasondetailsid) {
		this.reasondetailsid = reasondetailsid;
	}

	@Column(name = "reasondescription", nullable = false, length = 250)
	public String getReasondescription() {
		return this.reasondescription;
	}

	public void setReasondescription(String reasondescription) {
		this.reasondescription = reasondescription;
	}

	@Column(name = "valid", nullable = false)
	public boolean isValid() {
		return this.valid;
	}

	public void setValid(boolean valid) {
		this.valid = valid;
	}

	@Column(name = "updatedby", nullable = false, length = 150)
	public String getUpdatedby() {
		return this.updatedby;
	}

	public void setUpdatedby(String updatedby) {
		this.updatedby = updatedby;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updateddate", nullable = false, length = 29)
	public Date getUpdateddate() {
		return this.updateddate;
	}

	public void setUpdateddate(Date updateddate) {
		this.updateddate = updateddate;
	}

	@Column(name = "updatedip", nullable = false, length = 150)
	public String getUpdatedip() {
		return this.updatedip;
	}

	public void setUpdatedip(String updatedip) {
		this.updatedip = updatedip;
	}

}
