package com.leonia.wellness.entity;

// Generated 2 Jul, 2016 7:32:27 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.Generated;
import org.hibernate.annotations.GenerationTime;

/**
 * Segmentmaster generated by hbm2java
 */
@Entity
@Table(name = "segmentmaster")
public class Segmentmaster implements java.io.Serializable {

	private int segmentid;
	private int sno;
	private String segmentname;
	private String description;
	private boolean valid;
	private String updatedby;
	private Date updateddate;
	private String updatedip;
	private Set<Guestmaster> guestmasters = new HashSet<Guestmaster>(0);
	private Set<Appointment> appointments = new HashSet<Appointment>(0);

	public Segmentmaster() {
	}

	public Segmentmaster(int segmentid, int sno, boolean valid,
			String updatedby, Date updateddate, String updatedip) {
		this.segmentid = segmentid;
		this.sno = sno;
		this.valid = valid;
		this.updatedby = updatedby;
		this.updateddate = updateddate;
		this.updatedip = updatedip;
	}

	public Segmentmaster(int segmentid, int sno, String segmentname,
			String description, boolean valid, String updatedby,
			Date updateddate, String updatedip, Set<Guestmaster> guestmasters,
			Set<Appointment> appointments) {
		this.segmentid = segmentid;
		this.sno = sno;
		this.segmentname = segmentname;
		this.description = description;
		this.valid = valid;
		this.updatedby = updatedby;
		this.updateddate = updateddate;
		this.updatedip = updatedip;
		this.guestmasters = guestmasters;
		this.appointments = appointments;
	}

	@Id
	@Column(name = "segmentid", unique = true, nullable = false)
	public int getSegmentid() {
		return this.segmentid;
	}

	public void setSegmentid(int segmentid) {
		this.segmentid = segmentid;
	}

	@Generated(GenerationTime.INSERT)
	@Column(name = "sno", insertable = false, nullable = false)
	public int getSno() {
		return this.sno;
	}

	public void setSno(int sno) {
		this.sno = sno;
	}

	@Column(name = "segmentname", length = 200)
	public String getSegmentname() {
		return this.segmentname;
	}

	public void setSegmentname(String segmentname) {
		this.segmentname = segmentname;
	}

	@Column(name = "description")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "valid", nullable = false)
	public boolean isValid() {
		return this.valid;
	}

	public void setValid(boolean valid) {
		this.valid = valid;
	}

	@Column(name = "updatedby", nullable = false, length = 150)
	public String getUpdatedby() {
		return this.updatedby;
	}

	public void setUpdatedby(String updatedby) {
		this.updatedby = updatedby;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updateddate", nullable = false, length = 29)
	public Date getUpdateddate() {
		return this.updateddate;
	}

	public void setUpdateddate(Date updateddate) {
		this.updateddate = updateddate;
	}

	@Column(name = "updatedip", nullable = false, length = 150)
	public String getUpdatedip() {
		return this.updatedip;
	}

	public void setUpdatedip(String updatedip) {
		this.updatedip = updatedip;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "segmentmaster")
	public Set<Guestmaster> getGuestmasters() {
		return this.guestmasters;
	}

	public void setGuestmasters(Set<Guestmaster> guestmasters) {
		this.guestmasters = guestmasters;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "segmentmaster")
	public Set<Appointment> getAppointments() {
		return this.appointments;
	}

	public void setAppointments(Set<Appointment> appointments) {
		this.appointments = appointments;
	}

}
