package com.leonia.wellness.entity;

// Generated 20 Jul, 2016 3:39:07 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.Generated;
import org.hibernate.annotations.GenerationTime;

/**
 * Servicestocksmaster generated by hbm2java
 */
@Entity
@Table(name = "servicestocksmaster")
public class Servicestocksmaster implements java.io.Serializable {

	private int servicestockid;
	private Servicemaster servicemaster;
	private Stockmaster stockmaster;
	private int sno;
	private BigDecimal stockusage;
	private boolean valid;
	private String updatedby;
	private Date updateddate;
	private String updatedip;

	public Servicestocksmaster() {
	}

	public Servicestocksmaster(int servicestockid, Servicemaster servicemaster,
			Stockmaster stockmaster, int sno, BigDecimal stockusage,
			boolean valid, String updatedby, Date updateddate, String updatedip) {
		this.servicestockid = servicestockid;
		this.servicemaster = servicemaster;
		this.stockmaster = stockmaster;
		this.sno = sno;
		this.stockusage = stockusage;
		this.valid = valid;
		this.updatedby = updatedby;
		this.updateddate = updateddate;
		this.updatedip = updatedip;
	}

	@Id
	@Column(name = "servicestockid", unique = true, nullable = false)
	public int getServicestockid() {
		return this.servicestockid;
	}

	public void setServicestockid(int servicestockid) {
		this.servicestockid = servicestockid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "serviceid", nullable = false)
	public Servicemaster getServicemaster() {
		return this.servicemaster;
	}

	public void setServicemaster(Servicemaster servicemaster) {
		this.servicemaster = servicemaster;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "stockid", nullable = false)
	public Stockmaster getStockmaster() {
		return this.stockmaster;
	}

	public void setStockmaster(Stockmaster stockmaster) {
		this.stockmaster = stockmaster;
	}

	@Generated(GenerationTime.INSERT)
	@Column(name = "sno", insertable = false, nullable = false)
	public int getSno() {
		return this.sno;
	}

	public void setSno(int sno) {
		this.sno = sno;
	}

	@Column(name = "stockusage", nullable = false, precision = 15, scale = 3)
	public BigDecimal getStockusage() {
		return this.stockusage;
	}

	public void setStockusage(BigDecimal stockusage) {
		this.stockusage = stockusage;
	}

	@Column(name = "valid", nullable = false)
	public boolean isValid() {
		return this.valid;
	}

	public void setValid(boolean valid) {
		this.valid = valid;
	}

	@Column(name = "updatedby", nullable = false, length = 150)
	public String getUpdatedby() {
		return this.updatedby;
	}

	public void setUpdatedby(String updatedby) {
		this.updatedby = updatedby;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updateddate", nullable = false, length = 29)
	public Date getUpdateddate() {
		return this.updateddate;
	}

	public void setUpdateddate(Date updateddate) {
		this.updateddate = updateddate;
	}

	@Column(name = "updatedip", nullable = false, length = 150)
	public String getUpdatedip() {
		return this.updatedip;
	}

	public void setUpdatedip(String updatedip) {
		this.updatedip = updatedip;
	}

}
