package com.leonia.wellness.entity;
// Generated Aug 20, 2016 2:52:14 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.Generated;
import org.hibernate.annotations.GenerationTime;

/**
 * Servicemaster generated by hbm2java
 */
@Entity
@Table(name = "servicemaster")
public class Servicemaster implements java.io.Serializable {

	private int serviceid;
	private Dropdowndetails dropdowndetails;
	private Servicegroupmaster servicegroupmaster;
	private int sno;
	private String servicename;
	private String preparetime;
	private String servicetime;
	private String waitingtime;
	private String cleaningtime;
	private String totalservicetime;
	private boolean valid;
	private String updatedby;
	private Date updateddate;
	private String updatedip;
	private Integer remainderdays;
	private Set<Guesthistoryservices> guesthistoryserviceses = new HashSet<Guesthistoryservices>(0);
	private Set<Serviceroommaster> serviceroommasters = new HashSet<Serviceroommaster>(0);
	private Set<Packageservices> packageserviceses = new HashSet<Packageservices>(0);
	private Set<Appointmentservicedetails> appointmentservicedetailses = new HashSet<Appointmentservicedetails>(0);
	private Set<Serviceratemaster> serviceratemasters = new HashSet<Serviceratemaster>(0);
	private Set<Servicestaffmaster> servicestaffmasters = new HashSet<Servicestaffmaster>(0);
	private Set<Billdetails> billdetailses = new HashSet<Billdetails>(0);
	private Set<Servicestocksmaster> servicestocksmasters = new HashSet<Servicestocksmaster>(0);
	private Set<Appointmentstockconsumption> appointmentstockconsumptions = new HashSet<Appointmentstockconsumption>(0);

	public Servicemaster() {
	}

	public Servicemaster(int serviceid, Servicegroupmaster servicegroupmaster, int sno, String servicename,
			String preparetime, String servicetime, String waitingtime, String cleaningtime, String totalservicetime,
			boolean valid, String updatedby, Date updateddate, String updatedip) {
		this.serviceid = serviceid;
		this.servicegroupmaster = servicegroupmaster;
		this.sno = sno;
		this.servicename = servicename;
		this.preparetime = preparetime;
		this.servicetime = servicetime;
		this.waitingtime = waitingtime;
		this.cleaningtime = cleaningtime;
		this.totalservicetime = totalservicetime;
		this.valid = valid;
		this.updatedby = updatedby;
		this.updateddate = updateddate;
		this.updatedip = updatedip;
	}

	public Servicemaster(int serviceid, Dropdowndetails dropdowndetails, Servicegroupmaster servicegroupmaster, int sno,
			String servicename, String preparetime, String servicetime, String waitingtime, String cleaningtime,
			String totalservicetime, boolean valid, String updatedby, Date updateddate, String updatedip,
			Integer remainderdays, Set<Guesthistoryservices> guesthistoryserviceses,
			Set<Serviceroommaster> serviceroommasters, Set<Packageservices> packageserviceses,
			Set<Appointmentservicedetails> appointmentservicedetailses, Set<Serviceratemaster> serviceratemasters,
			Set<Servicestaffmaster> servicestaffmasters, Set<Billdetails> billdetailses,
			Set<Servicestocksmaster> servicestocksmasters,
			Set<Appointmentstockconsumption> appointmentstockconsumptions) {
		this.serviceid = serviceid;
		this.dropdowndetails = dropdowndetails;
		this.servicegroupmaster = servicegroupmaster;
		this.sno = sno;
		this.servicename = servicename;
		this.preparetime = preparetime;
		this.servicetime = servicetime;
		this.waitingtime = waitingtime;
		this.cleaningtime = cleaningtime;
		this.totalservicetime = totalservicetime;
		this.valid = valid;
		this.updatedby = updatedby;
		this.updateddate = updateddate;
		this.updatedip = updatedip;
		this.remainderdays = remainderdays;
		this.guesthistoryserviceses = guesthistoryserviceses;
		this.serviceroommasters = serviceroommasters;
		this.packageserviceses = packageserviceses;
		this.appointmentservicedetailses = appointmentservicedetailses;
		this.serviceratemasters = serviceratemasters;
		this.servicestaffmasters = servicestaffmasters;
		this.billdetailses = billdetailses;
		this.servicestocksmasters = servicestocksmasters;
		this.appointmentstockconsumptions = appointmentstockconsumptions;
	}

	@Id

	@Column(name = "serviceid", unique = true, nullable = false)
	public int getServiceid() {
		return this.serviceid;
	}

	public void setServiceid(int serviceid) {
		this.serviceid = serviceid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "genderid")
	public Dropdowndetails getDropdowndetails() {
		return this.dropdowndetails;
	}

	public void setDropdowndetails(Dropdowndetails dropdowndetails) {
		this.dropdowndetails = dropdowndetails;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "servicegroupid", nullable = false)
	public Servicegroupmaster getServicegroupmaster() {
		return this.servicegroupmaster;
	}

	public void setServicegroupmaster(Servicegroupmaster servicegroupmaster) {
		this.servicegroupmaster = servicegroupmaster;
	}

	@Generated(GenerationTime.INSERT)
	@Column(name = "sno", insertable = false, nullable = false)
	public int getSno() {
		return this.sno;
	}

	public void setSno(int sno) {
		this.sno = sno;
	}

	@Column(name = "servicename", nullable = false, length = 300)
	public String getServicename() {
		return this.servicename;
	}

	public void setServicename(String servicename) {
		this.servicename = servicename;
	}

	@Column(name = "preparetime", nullable = false, length = 100)
	public String getPreparetime() {
		return this.preparetime;
	}

	public void setPreparetime(String preparetime) {
		this.preparetime = preparetime;
	}

	@Column(name = "servicetime", nullable = false, length = 100)
	public String getServicetime() {
		return this.servicetime;
	}

	public void setServicetime(String servicetime) {
		this.servicetime = servicetime;
	}

	@Column(name = "waitingtime", nullable = false, length = 100)
	public String getWaitingtime() {
		return this.waitingtime;
	}

	public void setWaitingtime(String waitingtime) {
		this.waitingtime = waitingtime;
	}

	@Column(name = "cleaningtime", nullable = false, length = 100)
	public String getCleaningtime() {
		return this.cleaningtime;
	}

	public void setCleaningtime(String cleaningtime) {
		this.cleaningtime = cleaningtime;
	}

	@Column(name = "totalservicetime", nullable = false, length = 100)
	public String getTotalservicetime() {
		return this.totalservicetime;
	}

	public void setTotalservicetime(String totalservicetime) {
		this.totalservicetime = totalservicetime;
	}

	@Column(name = "valid", nullable = false)
	public boolean isValid() {
		return this.valid;
	}

	public void setValid(boolean valid) {
		this.valid = valid;
	}

	@Column(name = "updatedby", nullable = false, length = 150)
	public String getUpdatedby() {
		return this.updatedby;
	}

	public void setUpdatedby(String updatedby) {
		this.updatedby = updatedby;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updateddate", nullable = false, length = 29)
	public Date getUpdateddate() {
		return this.updateddate;
	}

	public void setUpdateddate(Date updateddate) {
		this.updateddate = updateddate;
	}

	@Column(name = "updatedip", nullable = false, length = 150)
	public String getUpdatedip() {
		return this.updatedip;
	}

	public void setUpdatedip(String updatedip) {
		this.updatedip = updatedip;
	}

	@Column(name = "remainderdays")
	public Integer getRemainderdays() {
		return this.remainderdays;
	}

	public void setRemainderdays(Integer remainderdays) {
		this.remainderdays = remainderdays;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "servicemaster")
	public Set<Guesthistoryservices> getGuesthistoryserviceses() {
		return this.guesthistoryserviceses;
	}

	public void setGuesthistoryserviceses(Set<Guesthistoryservices> guesthistoryserviceses) {
		this.guesthistoryserviceses = guesthistoryserviceses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "servicemaster")
	public Set<Serviceroommaster> getServiceroommasters() {
		return this.serviceroommasters;
	}

	public void setServiceroommasters(Set<Serviceroommaster> serviceroommasters) {
		this.serviceroommasters = serviceroommasters;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "servicemaster")
	public Set<Packageservices> getPackageserviceses() {
		return this.packageserviceses;
	}

	public void setPackageserviceses(Set<Packageservices> packageserviceses) {
		this.packageserviceses = packageserviceses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "servicemaster")
	public Set<Appointmentservicedetails> getAppointmentservicedetailses() {
		return this.appointmentservicedetailses;
	}

	public void setAppointmentservicedetailses(Set<Appointmentservicedetails> appointmentservicedetailses) {
		this.appointmentservicedetailses = appointmentservicedetailses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "servicemaster")
	public Set<Serviceratemaster> getServiceratemasters() {
		return this.serviceratemasters;
	}

	public void setServiceratemasters(Set<Serviceratemaster> serviceratemasters) {
		this.serviceratemasters = serviceratemasters;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "servicemaster")
	public Set<Servicestaffmaster> getServicestaffmasters() {
		return this.servicestaffmasters;
	}

	public void setServicestaffmasters(Set<Servicestaffmaster> servicestaffmasters) {
		this.servicestaffmasters = servicestaffmasters;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "servicemaster")
	public Set<Billdetails> getBilldetailses() {
		return this.billdetailses;
	}

	public void setBilldetailses(Set<Billdetails> billdetailses) {
		this.billdetailses = billdetailses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "servicemaster")
	public Set<Servicestocksmaster> getServicestocksmasters() {
		return this.servicestocksmasters;
	}

	public void setServicestocksmasters(Set<Servicestocksmaster> servicestocksmasters) {
		this.servicestocksmasters = servicestocksmasters;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "servicemaster")
	public Set<Appointmentstockconsumption> getAppointmentstockconsumptions() {
		return this.appointmentstockconsumptions;
	}

	public void setAppointmentstockconsumptions(Set<Appointmentstockconsumption> appointmentstockconsumptions) {
		this.appointmentstockconsumptions = appointmentstockconsumptions;
	}

}
