package com.leonia.wellness.entity;

// Generated 2 Jul, 2016 7:32:27 PM by Hibernate Tools 4.3.1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.Generated;
import org.hibernate.annotations.GenerationTime;

/**
 * Serviceroommaster generated by hbm2java
 */
@Entity
@Table(name = "serviceroommaster")
public class Serviceroommaster implements java.io.Serializable {

	private int serviceroomid;
	private Roommaster roommaster;
	private Servicemaster servicemaster;
	private int sno;
	private String description;
	private boolean valid;
	private String updatedby;
	private Date updateddate;
	private String updatedip;

	public Serviceroommaster() {
	}

	public Serviceroommaster(int serviceroomid, Roommaster roommaster,
			Servicemaster servicemaster, int sno, boolean valid,
			String updatedby, Date updateddate, String updatedip) {
		this.serviceroomid = serviceroomid;
		this.roommaster = roommaster;
		this.servicemaster = servicemaster;
		this.sno = sno;
		this.valid = valid;
		this.updatedby = updatedby;
		this.updateddate = updateddate;
		this.updatedip = updatedip;
	}

	public Serviceroommaster(int serviceroomid, Roommaster roommaster,
			Servicemaster servicemaster, int sno, String description,
			boolean valid, String updatedby, Date updateddate, String updatedip) {
		this.serviceroomid = serviceroomid;
		this.roommaster = roommaster;
		this.servicemaster = servicemaster;
		this.sno = sno;
		this.description = description;
		this.valid = valid;
		this.updatedby = updatedby;
		this.updateddate = updateddate;
		this.updatedip = updatedip;
	}

	@Id
	@Column(name = "serviceroomid", unique = true, nullable = false)
	public int getServiceroomid() {
		return this.serviceroomid;
	}

	public void setServiceroomid(int serviceroomid) {
		this.serviceroomid = serviceroomid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "roomid", nullable = false)
	public Roommaster getRoommaster() {
		return this.roommaster;
	}

	public void setRoommaster(Roommaster roommaster) {
		this.roommaster = roommaster;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "serviceid", nullable = false)
	public Servicemaster getServicemaster() {
		return this.servicemaster;
	}

	public void setServicemaster(Servicemaster servicemaster) {
		this.servicemaster = servicemaster;
	}

	@Generated(GenerationTime.INSERT)
	@Column(name = "sno", insertable = false, nullable = false)
	public int getSno() {
		return this.sno;
	}

	public void setSno(int sno) {
		this.sno = sno;
	}

	@Column(name = "description")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "valid", nullable = false)
	public boolean isValid() {
		return this.valid;
	}

	public void setValid(boolean valid) {
		this.valid = valid;
	}

	@Column(name = "updatedby", nullable = false, length = 150)
	public String getUpdatedby() {
		return this.updatedby;
	}

	public void setUpdatedby(String updatedby) {
		this.updatedby = updatedby;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updateddate", nullable = false, length = 29)
	public Date getUpdateddate() {
		return this.updateddate;
	}

	public void setUpdateddate(Date updateddate) {
		this.updateddate = updateddate;
	}

	@Column(name = "updatedip", nullable = false, length = 150)
	public String getUpdatedip() {
		return this.updatedip;
	}

	public void setUpdatedip(String updatedip) {
		this.updatedip = updatedip;
	}

}
