package com.leonia.wellness.entity;

// Generated 20 Jul, 2016 3:39:07 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.Generated;
import org.hibernate.annotations.GenerationTime;

/**
 * Serviceratemaster generated by hbm2java
 */
@Entity
@Table(name = "serviceratemaster")
public class Serviceratemaster implements java.io.Serializable {

	private int servicerateid;
	private Servicemaster servicemaster;
	private Taxstructuremaster taxstructuremaster;
	private int sno;
	private BigDecimal servicecost;
	private int taxstructureid;
	private Date applicabledate;
	private boolean valid;
	private String updatedby;
	private Date updateddate;
	private String updatedip;

	public Serviceratemaster() {
	}

	public Serviceratemaster(int servicerateid, Servicemaster servicemaster,
			Taxstructuremaster taxstructuremaster, int sno,
			BigDecimal servicecost, int taxstructureid, Date applicabledate,
			boolean valid, String updatedby, Date updateddate, String updatedip) {
		this.servicerateid = servicerateid;
		this.servicemaster = servicemaster;
		this.taxstructuremaster = taxstructuremaster;
		this.sno = sno;
		this.servicecost = servicecost;
		this.taxstructureid = taxstructureid;
		this.applicabledate = applicabledate;
		this.valid = valid;
		this.updatedby = updatedby;
		this.updateddate = updateddate;
		this.updatedip = updatedip;
	}

	@Id
	@Column(name = "servicerateid", unique = true, nullable = false)
	public int getServicerateid() {
		return this.servicerateid;
	}

	public void setServicerateid(int servicerateid) {
		this.servicerateid = servicerateid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "serviceid", nullable = false)
	public Servicemaster getServicemaster() {
		return this.servicemaster;
	}

	public void setServicemaster(Servicemaster servicemaster) {
		this.servicemaster = servicemaster;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "taxstructurecode", nullable = false)
	public Taxstructuremaster getTaxstructuremaster() {
		return this.taxstructuremaster;
	}

	public void setTaxstructuremaster(Taxstructuremaster taxstructuremaster) {
		this.taxstructuremaster = taxstructuremaster;
	}

	@Generated(GenerationTime.INSERT)
	@Column(name = "sno", insertable = false, nullable = false)
	public int getSno() {
		return this.sno;
	}

	public void setSno(int sno) {
		this.sno = sno;
	}

	@Column(name = "servicecost", nullable = false, precision = 15)
	public BigDecimal getServicecost() {
		return this.servicecost;
	}

	public void setServicecost(BigDecimal servicecost) {
		this.servicecost = servicecost;
	}

	@Column(name = "taxstructureid", nullable = false)
	public int getTaxstructureid() {
		return this.taxstructureid;
	}

	public void setTaxstructureid(int taxstructureid) {
		this.taxstructureid = taxstructureid;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "applicabledate", nullable = false, length = 13)
	public Date getApplicabledate() {
		return this.applicabledate;
	}

	public void setApplicabledate(Date applicabledate) {
		this.applicabledate = applicabledate;
	}

	@Column(name = "valid", nullable = false)
	public boolean isValid() {
		return this.valid;
	}

	public void setValid(boolean valid) {
		this.valid = valid;
	}

	@Column(name = "updatedby", nullable = false, length = 150)
	public String getUpdatedby() {
		return this.updatedby;
	}

	public void setUpdatedby(String updatedby) {
		this.updatedby = updatedby;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updateddate", nullable = false, length = 29)
	public Date getUpdateddate() {
		return this.updateddate;
	}

	public void setUpdateddate(Date updateddate) {
		this.updateddate = updateddate;
	}

	@Column(name = "updatedip", nullable = false, length = 150)
	public String getUpdatedip() {
		return this.updatedip;
	}

	public void setUpdatedip(String updatedip) {
		this.updatedip = updatedip;
	}

}
