package com.leonia.wellness.entity;

// Generated 29 Jul, 2016 3:49:40 PM by Hibernate Tools 4.3.1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.Generated;
import org.hibernate.annotations.GenerationTime;

/**
 * Servicestaffmaster generated by hbm2java
 */
@Entity
@Table(name = "servicestaffmaster")
public class Servicestaffmaster implements java.io.Serializable {

	private int servicestaffid;
	private Servicemaster servicemaster;
	private Staffmaster staffmaster;
	private int sno;
	private String description;
	private boolean valid;
	private String updatedby;
	private Date updateddate;
	private String updatedip;

	public Servicestaffmaster() {
	}

	public Servicestaffmaster(int servicestaffid, Servicemaster servicemaster,
			Staffmaster staffmaster, int sno, boolean valid, String updatedby,
			Date updateddate, String updatedip) {
		this.servicestaffid = servicestaffid;
		this.servicemaster = servicemaster;
		this.staffmaster = staffmaster;
		this.sno = sno;
		this.valid = valid;
		this.updatedby = updatedby;
		this.updateddate = updateddate;
		this.updatedip = updatedip;
	}

	public Servicestaffmaster(int servicestaffid, Servicemaster servicemaster,
			Staffmaster staffmaster, int sno, String description,
			boolean valid, String updatedby, Date updateddate, String updatedip) {
		this.servicestaffid = servicestaffid;
		this.servicemaster = servicemaster;
		this.staffmaster = staffmaster;
		this.sno = sno;
		this.description = description;
		this.valid = valid;
		this.updatedby = updatedby;
		this.updateddate = updateddate;
		this.updatedip = updatedip;
	}

	@Id
	@Column(name = "servicestaffid", unique = true, nullable = false)
	public int getServicestaffid() {
		return this.servicestaffid;
	}

	public void setServicestaffid(int servicestaffid) {
		this.servicestaffid = servicestaffid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "serviceid", nullable = false)
	public Servicemaster getServicemaster() {
		return this.servicemaster;
	}

	public void setServicemaster(Servicemaster servicemaster) {
		this.servicemaster = servicemaster;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "staffid", nullable = false)
	public Staffmaster getStaffmaster() {
		return this.staffmaster;
	}

	public void setStaffmaster(Staffmaster staffmaster) {
		this.staffmaster = staffmaster;
	}

	@Generated(GenerationTime.INSERT)
	@Column(name = "sno", insertable = false, nullable = false)
	public int getSno() {
		return this.sno;
	}

	public void setSno(int sno) {
		this.sno = sno;
	}

	@Column(name = "description")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "valid", nullable = false)
	public boolean isValid() {
		return this.valid;
	}

	public void setValid(boolean valid) {
		this.valid = valid;
	}

	@Column(name = "updatedby", nullable = false, length = 150)
	public String getUpdatedby() {
		return this.updatedby;
	}

	public void setUpdatedby(String updatedby) {
		this.updatedby = updatedby;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updateddate", nullable = false, length = 29)
	public Date getUpdateddate() {
		return this.updateddate;
	}

	public void setUpdateddate(Date updateddate) {
		this.updateddate = updateddate;
	}

	@Column(name = "updatedip", nullable = false, length = 150)
	public String getUpdatedip() {
		return this.updatedip;
	}

	public void setUpdatedip(String updatedip) {
		this.updatedip = updatedip;
	}

}
