package com.leonia.wellness.entity;

// Generated 8 Aug, 2016 12:23:20 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.Generated;
import org.hibernate.annotations.GenerationTime;

/**
 * Statusmaster generated by hbm2java
 */
@Entity
@Table(name = "statusmaster")
public class Statusmaster implements java.io.Serializable {

	private int statusid;
	private int sno;
	private String statusdescription;
	private boolean valid;
	private String updatedby;
	private Date updateddate;
	private String updatedip;
	private Set<Appointment> appointments = new HashSet<Appointment>(0);
	private Set<Appointmentservicedetails> appointmentservicedetailses = new HashSet<Appointmentservicedetails>(
			0);
	private Set<Ticketmaster> ticketmasters = new HashSet<Ticketmaster>(0);

	public Statusmaster() {
	}

	public Statusmaster(int statusid, int sno, String statusdescription,
			boolean valid, String updatedby, Date updateddate, String updatedip) {
		this.statusid = statusid;
		this.sno = sno;
		this.statusdescription = statusdescription;
		this.valid = valid;
		this.updatedby = updatedby;
		this.updateddate = updateddate;
		this.updatedip = updatedip;
	}

	public Statusmaster(int statusid, int sno, String statusdescription,
			boolean valid, String updatedby, Date updateddate,
			String updatedip, Set<Appointment> appointments,
			Set<Appointmentservicedetails> appointmentservicedetailses,
			Set<Ticketmaster> ticketmasters) {
		this.statusid = statusid;
		this.sno = sno;
		this.statusdescription = statusdescription;
		this.valid = valid;
		this.updatedby = updatedby;
		this.updateddate = updateddate;
		this.updatedip = updatedip;
		this.appointments = appointments;
		this.appointmentservicedetailses = appointmentservicedetailses;
		this.ticketmasters = ticketmasters;
	}

	@Id
	@Column(name = "statusid", unique = true, nullable = false)
	public int getStatusid() {
		return this.statusid;
	}

	public void setStatusid(int statusid) {
		this.statusid = statusid;
	}

	@Generated(GenerationTime.INSERT)
	@Column(name = "sno", insertable = false, nullable = false)
	public int getSno() {
		return this.sno;
	}

	public void setSno(int sno) {
		this.sno = sno;
	}

	@Column(name = "statusdescription", nullable = false, length = 200)
	public String getStatusdescription() {
		return this.statusdescription;
	}

	public void setStatusdescription(String statusdescription) {
		this.statusdescription = statusdescription;
	}

	@Column(name = "valid", nullable = false)
	public boolean isValid() {
		return this.valid;
	}

	public void setValid(boolean valid) {
		this.valid = valid;
	}

	@Column(name = "updatedby", nullable = false, length = 150)
	public String getUpdatedby() {
		return this.updatedby;
	}

	public void setUpdatedby(String updatedby) {
		this.updatedby = updatedby;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updateddate", nullable = false, length = 29)
	public Date getUpdateddate() {
		return this.updateddate;
	}

	public void setUpdateddate(Date updateddate) {
		this.updateddate = updateddate;
	}

	@Column(name = "updatedip", nullable = false, length = 150)
	public String getUpdatedip() {
		return this.updatedip;
	}

	public void setUpdatedip(String updatedip) {
		this.updatedip = updatedip;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "statusmaster")
	public Set<Appointment> getAppointments() {
		return this.appointments;
	}

	public void setAppointments(Set<Appointment> appointments) {
		this.appointments = appointments;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "statusmaster")
	public Set<Appointmentservicedetails> getAppointmentservicedetailses() {
		return this.appointmentservicedetailses;
	}

	public void setAppointmentservicedetailses(
			Set<Appointmentservicedetails> appointmentservicedetailses) {
		this.appointmentservicedetailses = appointmentservicedetailses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "statusmaster")
	public Set<Ticketmaster> getTicketmasters() {
		return this.ticketmasters;
	}

	public void setTicketmasters(Set<Ticketmaster> ticketmasters) {
		this.ticketmasters = ticketmasters;
	}

}
