package com.leonia.wellness.entity;

// Generated 2 Jul, 2016 7:32:27 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.Generated;
import org.hibernate.annotations.GenerationTime;

/**
 * Stocksubgroupmaster generated by hbm2java
 */
@Entity
@Table(name = "stocksubgroupmaster")
public class Stocksubgroupmaster implements java.io.Serializable {

	private int stocksubgroupid;
	private Stockgroupmaster stockgroupmaster;
	private int sno;
	private String stocksubgroupname;
	private String description;
	private boolean valid;
	private String updatedby;
	private Date updateddate;
	private String updatedip;
	private Set<Stockmaster> stockmasters = new HashSet<Stockmaster>(0);

	public Stocksubgroupmaster() {
	}

	public Stocksubgroupmaster(int stocksubgroupid,
			Stockgroupmaster stockgroupmaster, int sno,
			String stocksubgroupname, boolean valid, String updatedby,
			Date updateddate, String updatedip) {
		this.stocksubgroupid = stocksubgroupid;
		this.stockgroupmaster = stockgroupmaster;
		this.sno = sno;
		this.stocksubgroupname = stocksubgroupname;
		this.valid = valid;
		this.updatedby = updatedby;
		this.updateddate = updateddate;
		this.updatedip = updatedip;
	}

	public Stocksubgroupmaster(int stocksubgroupid,
			Stockgroupmaster stockgroupmaster, int sno,
			String stocksubgroupname, String description, boolean valid,
			String updatedby, Date updateddate, String updatedip,
			Set<Stockmaster> stockmasters) {
		this.stocksubgroupid = stocksubgroupid;
		this.stockgroupmaster = stockgroupmaster;
		this.sno = sno;
		this.stocksubgroupname = stocksubgroupname;
		this.description = description;
		this.valid = valid;
		this.updatedby = updatedby;
		this.updateddate = updateddate;
		this.updatedip = updatedip;
		this.stockmasters = stockmasters;
	}

	@Id
	@Column(name = "stocksubgroupid", unique = true, nullable = false)
	public int getStocksubgroupid() {
		return this.stocksubgroupid;
	}

	public void setStocksubgroupid(int stocksubgroupid) {
		this.stocksubgroupid = stocksubgroupid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "stockgroupid", nullable = false)
	public Stockgroupmaster getStockgroupmaster() {
		return this.stockgroupmaster;
	}

	public void setStockgroupmaster(Stockgroupmaster stockgroupmaster) {
		this.stockgroupmaster = stockgroupmaster;
	}

	@Generated(GenerationTime.INSERT)
	@Column(name = "sno", insertable = false, nullable = false)
	public int getSno() {
		return this.sno;
	}

	public void setSno(int sno) {
		this.sno = sno;
	}

	@Column(name = "stocksubgroupname", nullable = false, length = 150)
	public String getStocksubgroupname() {
		return this.stocksubgroupname;
	}

	public void setStocksubgroupname(String stocksubgroupname) {
		this.stocksubgroupname = stocksubgroupname;
	}

	@Column(name = "description")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "valid", nullable = false)
	public boolean isValid() {
		return this.valid;
	}

	public void setValid(boolean valid) {
		this.valid = valid;
	}

	@Column(name = "updatedby", nullable = false, length = 150)
	public String getUpdatedby() {
		return this.updatedby;
	}

	public void setUpdatedby(String updatedby) {
		this.updatedby = updatedby;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updateddate", nullable = false, length = 29)
	public Date getUpdateddate() {
		return this.updateddate;
	}

	public void setUpdateddate(Date updateddate) {
		this.updateddate = updateddate;
	}

	@Column(name = "updatedip", nullable = false, length = 150)
	public String getUpdatedip() {
		return this.updatedip;
	}

	public void setUpdatedip(String updatedip) {
		this.updatedip = updatedip;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "stocksubgroupmaster")
	public Set<Stockmaster> getStockmasters() {
		return this.stockmasters;
	}

	public void setStockmasters(Set<Stockmaster> stockmasters) {
		this.stockmasters = stockmasters;
	}

}
