package com.leonia.wellness.entity;

// Generated 2 Jul, 2016 7:32:27 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.Generated;
import org.hibernate.annotations.GenerationTime;

/**
 * Stockgroupmaster generated by hbm2java
 */
@Entity
@Table(name = "stockgroupmaster")
public class Stockgroupmaster implements java.io.Serializable {

	private int stockgroupid;
	private int sno;
	private String stockgroupname;
	private String description;
	private boolean valid;
	private String updatedby;
	private Date updateddate;
	private String updatedip;
	private Set<Stocksubgroupmaster> stocksubgroupmasters = new HashSet<Stocksubgroupmaster>(
			0);

	public Stockgroupmaster() {
	}

	public Stockgroupmaster(int stockgroupid, int sno, String stockgroupname,
			boolean valid, String updatedby, Date updateddate, String updatedip) {
		this.stockgroupid = stockgroupid;
		this.sno = sno;
		this.stockgroupname = stockgroupname;
		this.valid = valid;
		this.updatedby = updatedby;
		this.updateddate = updateddate;
		this.updatedip = updatedip;
	}

	public Stockgroupmaster(int stockgroupid, int sno, String stockgroupname,
			String description, boolean valid, String updatedby,
			Date updateddate, String updatedip,
			Set<Stocksubgroupmaster> stocksubgroupmasters) {
		this.stockgroupid = stockgroupid;
		this.sno = sno;
		this.stockgroupname = stockgroupname;
		this.description = description;
		this.valid = valid;
		this.updatedby = updatedby;
		this.updateddate = updateddate;
		this.updatedip = updatedip;
		this.stocksubgroupmasters = stocksubgroupmasters;
	}

	@Id
	@Column(name = "stockgroupid", unique = true, nullable = false)
	public int getStockgroupid() {
		return this.stockgroupid;
	}

	public void setStockgroupid(int stockgroupid) {
		this.stockgroupid = stockgroupid;
	}

	@Generated(GenerationTime.INSERT)
	@Column(name = "sno", insertable = false, nullable = false)
	public int getSno() {
		return this.sno;
	}

	public void setSno(int sno) {
		this.sno = sno;
	}

	@Column(name = "stockgroupname", nullable = false, length = 150)
	public String getStockgroupname() {
		return this.stockgroupname;
	}

	public void setStockgroupname(String stockgroupname) {
		this.stockgroupname = stockgroupname;
	}

	@Column(name = "description")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "valid", nullable = false)
	public boolean isValid() {
		return this.valid;
	}

	public void setValid(boolean valid) {
		this.valid = valid;
	}

	@Column(name = "updatedby", nullable = false, length = 150)
	public String getUpdatedby() {
		return this.updatedby;
	}

	public void setUpdatedby(String updatedby) {
		this.updatedby = updatedby;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updateddate", nullable = false, length = 29)
	public Date getUpdateddate() {
		return this.updateddate;
	}

	public void setUpdateddate(Date updateddate) {
		this.updateddate = updateddate;
	}

	@Column(name = "updatedip", nullable = false, length = 150)
	public String getUpdatedip() {
		return this.updatedip;
	}

	public void setUpdatedip(String updatedip) {
		this.updatedip = updatedip;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "stockgroupmaster")
	public Set<Stocksubgroupmaster> getStocksubgroupmasters() {
		return this.stocksubgroupmasters;
	}

	public void setStocksubgroupmasters(
			Set<Stocksubgroupmaster> stocksubgroupmasters) {
		this.stocksubgroupmasters = stocksubgroupmasters;
	}

}
