package com.leonia.wellness.entity;

// Generated 2 Jul, 2016 7:32:27 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.Generated;
import org.hibernate.annotations.GenerationTime;

/**
 * Taxmaster generated by hbm2java
 */
@Entity
@Table(name = "taxmaster")
public class Taxmaster implements java.io.Serializable {

	private int taxmasterid;
	private int sno;
	private String taxname;
	private boolean valid;
	private String updatedby;
	private Date updateddate;
	private String updatedip;
	private Set<Taxstructuredetails> taxstructuredetailses = new HashSet<Taxstructuredetails>(
			0);

	public Taxmaster() {
	}

	public Taxmaster(int taxmasterid, int sno, String taxname, boolean valid,
			String updatedby, Date updateddate, String updatedip) {
		this.taxmasterid = taxmasterid;
		this.sno = sno;
		this.taxname = taxname;
		this.valid = valid;
		this.updatedby = updatedby;
		this.updateddate = updateddate;
		this.updatedip = updatedip;
	}

	public Taxmaster(int taxmasterid, int sno, String taxname, boolean valid,
			String updatedby, Date updateddate, String updatedip,
			Set<Taxstructuredetails> taxstructuredetailses) {
		this.taxmasterid = taxmasterid;
		this.sno = sno;
		this.taxname = taxname;
		this.valid = valid;
		this.updatedby = updatedby;
		this.updateddate = updateddate;
		this.updatedip = updatedip;
		this.taxstructuredetailses = taxstructuredetailses;
	}

	@Id
	@Column(name = "taxmasterid", unique = true, nullable = false)
	public int getTaxmasterid() {
		return this.taxmasterid;
	}

	public void setTaxmasterid(int taxmasterid) {
		this.taxmasterid = taxmasterid;
	}

	@Generated(GenerationTime.INSERT)
	@Column(name = "sno", insertable = false, nullable = false)
	public int getSno() {
		return this.sno;
	}

	public void setSno(int sno) {
		this.sno = sno;
	}

	@Column(name = "taxname", nullable = false, length = 100)
	public String getTaxname() {
		return this.taxname;
	}

	public void setTaxname(String taxname) {
		this.taxname = taxname;
	}

	@Column(name = "valid", nullable = false)
	public boolean isValid() {
		return this.valid;
	}

	public void setValid(boolean valid) {
		this.valid = valid;
	}

	@Column(name = "updatedby", nullable = false, length = 150)
	public String getUpdatedby() {
		return this.updatedby;
	}

	public void setUpdatedby(String updatedby) {
		this.updatedby = updatedby;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updateddate", nullable = false, length = 29)
	public Date getUpdateddate() {
		return this.updateddate;
	}

	public void setUpdateddate(Date updateddate) {
		this.updateddate = updateddate;
	}

	@Column(name = "updatedip", nullable = false, length = 150)
	public String getUpdatedip() {
		return this.updatedip;
	}

	public void setUpdatedip(String updatedip) {
		this.updatedip = updatedip;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "taxmaster")
	public Set<Taxstructuredetails> getTaxstructuredetailses() {
		return this.taxstructuredetailses;
	}

	public void setTaxstructuredetailses(
			Set<Taxstructuredetails> taxstructuredetailses) {
		this.taxstructuredetailses = taxstructuredetailses;
	}

}
