package com.leonia.wellness.entity;

// Generated 2 Jul, 2016 7:32:27 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.Generated;
import org.hibernate.annotations.GenerationTime;

/**
 * Taxmaster generated by hbm2java
 */
@Entity
@Table(name = "taxmasteraa")
public class Taxmasteraa implements java.io.Serializable {

	private int taxmasterid;
	private int sno;
	private String taxname;
	

	@Id
	@Column(name = "taxmasterid", unique = true, nullable = false)
	public int getTaxmasterid() {
		return this.taxmasterid;
	}

	public void setTaxmasterid(int taxmasterid) {
		this.taxmasterid = taxmasterid;
	}

	@Generated(GenerationTime.INSERT)
	@Column(name = "sno", insertable = false, nullable = false)
	public int getSno() {
		return this.sno;
	}

	public void setSno(int sno) {
		this.sno = sno;
	}

	@Column(name = "taxname", nullable = false, length = 100)
	public String getTaxname() {
		return this.taxname;
	}

	public void setTaxname(String taxname) {
		this.taxname = taxname;
	}

	

}
