package com.leonia.wellness.entity;

// Generated 15 Jul, 2016 11:20:07 AM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Taxstructuredetails generated by hbm2java
 */
@Entity
@Table(name = "taxstructuredetails")
public class Taxstructuredetails implements java.io.Serializable {

	private int sno;
	private Taxmaster taxmaster;
	private Taxstructuremaster taxstructuremaster;
	private int taxstructureid;
	private int taxdetailsid;
	private String taxdescription;
	private BigDecimal percent;
	private String taxtype;
	private String taxon;
	private boolean valid;
	private String updatedby;
	private Date updateddate;
	private String updatedip;

	public Taxstructuredetails() {
	}

	public Taxstructuredetails(int sno, Taxmaster taxmaster,
			Taxstructuremaster taxstructuremaster, int taxstructureid,
			int taxdetailsid, String taxdescription, BigDecimal percent,
			String taxtype, String taxon, boolean valid, String updatedby,
			Date updateddate, String updatedip) {
		this.sno = sno;
		this.taxmaster = taxmaster;
		this.taxstructuremaster = taxstructuremaster;
		this.taxstructureid = taxstructureid;
		this.taxdetailsid = taxdetailsid;
		this.taxdescription = taxdescription;
		this.percent = percent;
		this.taxtype = taxtype;
		this.taxon = taxon;
		this.valid = valid;
		this.updatedby = updatedby;
		this.updateddate = updateddate;
		this.updatedip = updatedip;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "sno", unique = true, insertable = false, nullable = false)
	public int getSno() {
		return this.sno;
	}

	public void setSno(int sno) {
		this.sno = sno;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "taxmasterid", nullable = false)
	public Taxmaster getTaxmaster() {
		return this.taxmaster;
	}

	public void setTaxmaster(Taxmaster taxmaster) {
		this.taxmaster = taxmaster;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "taxstructurecode", nullable = false)
	public Taxstructuremaster getTaxstructuremaster() {
		return this.taxstructuremaster;
	}

	public void setTaxstructuremaster(Taxstructuremaster taxstructuremaster) {
		this.taxstructuremaster = taxstructuremaster;
	}

	@Column(name = "taxstructureid", nullable = false)
	public int getTaxstructureid() {
		return this.taxstructureid;
	}

	public void setTaxstructureid(int taxstructureid) {
		this.taxstructureid = taxstructureid;
	}

	@Column(name = "taxdetailsid", nullable = false)
	public int getTaxdetailsid() {
		return this.taxdetailsid;
	}

	public void setTaxdetailsid(int taxdetailsid) {
		this.taxdetailsid = taxdetailsid;
	}

	@Column(name = "taxdescription", nullable = false, length = 150)
	public String getTaxdescription() {
		return this.taxdescription;
	}

	public void setTaxdescription(String taxdescription) {
		this.taxdescription = taxdescription;
	}

	@Column(name = "percent", nullable = false, precision = 5, scale = 3)
	public BigDecimal getPercent() {
		return this.percent;
	}

	public void setPercent(BigDecimal percent) {
		this.percent = percent;
	}

	@Column(name = "taxtype", nullable = false, length = 100)
	public String getTaxtype() {
		return this.taxtype;
	}

	public void setTaxtype(String taxtype) {
		this.taxtype = taxtype;
	}

	@Column(name = "taxon", nullable = false, length = 100)
	public String getTaxon() {
		return this.taxon;
	}

	public void setTaxon(String taxon) {
		this.taxon = taxon;
	}

	@Column(name = "valid", nullable = false)
	public boolean isValid() {
		return this.valid;
	}

	public void setValid(boolean valid) {
		this.valid = valid;
	}

	@Column(name = "updatedby", nullable = false, length = 150)
	public String getUpdatedby() {
		return this.updatedby;
	}

	public void setUpdatedby(String updatedby) {
		this.updatedby = updatedby;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updateddate", nullable = false, length = 29)
	public Date getUpdateddate() {
		return this.updateddate;
	}

	public void setUpdateddate(Date updateddate) {
		this.updateddate = updateddate;
	}

	@Column(name = "updatedip", nullable = false, length = 150)
	public String getUpdatedip() {
		return this.updatedip;
	}

	public void setUpdatedip(String updatedip) {
		this.updatedip = updatedip;
	}

}
