package com.leonia.wellness.entity;
// Generated Aug 20, 2016 4:14:06 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.Generated;
import org.hibernate.annotations.GenerationTime;

/**
 * Ticketmaster generated by hbm2java
 */
@Entity
@Table(name = "ticketmaster")
public class Ticketmaster implements java.io.Serializable {

	private int ticketno;
	private Billmaster billmaster;
	private Departmentmaster departmentmaster;
	private Feedbackformmaster feedbackformmaster;
	private Formmaster formmaster;
	private Guestmaster guestmaster;
	private Prioritymaster prioritymaster;
	private Responsemaster responsemaster;
	private Sbumaster sbumaster;
	private Staffmaster staffmaster;
	private Statusmaster statusmaster;
	private Tickettypemaster tickettypemaster;
	private int sno;
	private Integer questionid;
	private String complaint;
	private String remarks;
	private Date ticketdate;
	private Integer assignedto;
	private boolean valid;
	private String updatedby;
	private Date updateddate;
	private String updatedip;

	public Ticketmaster() {
	}

	public Ticketmaster(int ticketno, Departmentmaster departmentmaster, Prioritymaster prioritymaster,
			Statusmaster statusmaster, Tickettypemaster tickettypemaster, int sno, Date ticketdate, boolean valid,
			String updatedby, Date updateddate, String updatedip) {
		this.ticketno = ticketno;
		this.departmentmaster = departmentmaster;
		this.prioritymaster = prioritymaster;
		this.statusmaster = statusmaster;
		this.tickettypemaster = tickettypemaster;
		this.sno = sno;
		this.ticketdate = ticketdate;
		this.valid = valid;
		this.updatedby = updatedby;
		this.updateddate = updateddate;
		this.updatedip = updatedip;
	}

	public Ticketmaster(int ticketno, Billmaster billmaster, Departmentmaster departmentmaster,
			Feedbackformmaster feedbackformmaster, Formmaster formmaster, Guestmaster guestmaster,
			Prioritymaster prioritymaster, Responsemaster responsemaster, Sbumaster sbumaster, Staffmaster staffmaster,
			Statusmaster statusmaster, Tickettypemaster tickettypemaster, int sno, Integer questionid, String complaint,
			String remarks, Date ticketdate, Integer assignedto, boolean valid, String updatedby, Date updateddate,
			String updatedip) {
		this.ticketno = ticketno;
		this.billmaster = billmaster;
		this.departmentmaster = departmentmaster;
		this.feedbackformmaster = feedbackformmaster;
		this.formmaster = formmaster;
		this.guestmaster = guestmaster;
		this.prioritymaster = prioritymaster;
		this.responsemaster = responsemaster;
		this.sbumaster = sbumaster;
		this.staffmaster = staffmaster;
		this.statusmaster = statusmaster;
		this.tickettypemaster = tickettypemaster;
		this.sno = sno;
		this.questionid = questionid;
		this.complaint = complaint;
		this.remarks = remarks;
		this.ticketdate = ticketdate;
		this.assignedto = assignedto;
		this.valid = valid;
		this.updatedby = updatedby;
		this.updateddate = updateddate;
		this.updatedip = updatedip;
	}

	@Id

	@Column(name = "ticketno", unique = true, nullable = false)
	public int getTicketno() {
		return this.ticketno;
	}

	public void setTicketno(int ticketno) {
		this.ticketno = ticketno;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "billno")
	public Billmaster getBillmaster() {
		return this.billmaster;
	}

	public void setBillmaster(Billmaster billmaster) {
		this.billmaster = billmaster;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "departmentid", nullable = false)
	public Departmentmaster getDepartmentmaster() {
		return this.departmentmaster;
	}

	public void setDepartmentmaster(Departmentmaster departmentmaster) {
		this.departmentmaster = departmentmaster;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "feedbackformid")
	public Feedbackformmaster getFeedbackformmaster() {
		return this.feedbackformmaster;
	}

	public void setFeedbackformmaster(Feedbackformmaster feedbackformmaster) {
		this.feedbackformmaster = feedbackformmaster;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "formid")
	public Formmaster getFormmaster() {
		return this.formmaster;
	}

	public void setFormmaster(Formmaster formmaster) {
		this.formmaster = formmaster;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "guestid")
	public Guestmaster getGuestmaster() {
		return this.guestmaster;
	}

	public void setGuestmaster(Guestmaster guestmaster) {
		this.guestmaster = guestmaster;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "priorityid", nullable = false)
	public Prioritymaster getPrioritymaster() {
		return this.prioritymaster;
	}

	public void setPrioritymaster(Prioritymaster prioritymaster) {
		this.prioritymaster = prioritymaster;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "responseid")
	public Responsemaster getResponsemaster() {
		return this.responsemaster;
	}

	public void setResponsemaster(Responsemaster responsemaster) {
		this.responsemaster = responsemaster;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "sbuid")
	public Sbumaster getSbumaster() {
		return this.sbumaster;
	}

	public void setSbumaster(Sbumaster sbumaster) {
		this.sbumaster = sbumaster;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "staffid")
	public Staffmaster getStaffmaster() {
		return this.staffmaster;
	}

	public void setStaffmaster(Staffmaster staffmaster) {
		this.staffmaster = staffmaster;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ticketstatusid", nullable = false)
	public Statusmaster getStatusmaster() {
		return this.statusmaster;
	}

	public void setStatusmaster(Statusmaster statusmaster) {
		this.statusmaster = statusmaster;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "tickettypeid", nullable = false)
	public Tickettypemaster getTickettypemaster() {
		return this.tickettypemaster;
	}

	public void setTickettypemaster(Tickettypemaster tickettypemaster) {
		this.tickettypemaster = tickettypemaster;
	}

	@Generated(GenerationTime.INSERT)
	@Column(name = "sno", insertable = false, nullable = false)
	public int getSno() {
		return this.sno;
	}

	public void setSno(int sno) {
		this.sno = sno;
	}

	@Column(name = "questionid")
	public Integer getQuestionid() {
		return this.questionid;
	}

	public void setQuestionid(Integer questionid) {
		this.questionid = questionid;
	}

	@Column(name = "complaint")
	public String getComplaint() {
		return this.complaint;
	}

	public void setComplaint(String complaint) {
		this.complaint = complaint;
	}

	@Column(name = "remarks")
	public String getRemarks() {
		return this.remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "ticketdate", nullable = false, length = 13)
	public Date getTicketdate() {
		return this.ticketdate;
	}

	public void setTicketdate(Date ticketdate) {
		this.ticketdate = ticketdate;
	}

	@Column(name = "assignedto")
	public Integer getAssignedto() {
		return this.assignedto;
	}

	public void setAssignedto(Integer assignedto) {
		this.assignedto = assignedto;
	}

	@Column(name = "valid", nullable = false)
	public boolean isValid() {
		return this.valid;
	}

	public void setValid(boolean valid) {
		this.valid = valid;
	}

	@Column(name = "updatedby", nullable = false, length = 150)
	public String getUpdatedby() {
		return this.updatedby;
	}

	public void setUpdatedby(String updatedby) {
		this.updatedby = updatedby;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updateddate", nullable = false, length = 29)
	public Date getUpdateddate() {
		return this.updateddate;
	}

	public void setUpdateddate(Date updateddate) {
		this.updateddate = updateddate;
	}

	@Column(name = "updatedip", nullable = false, length = 150)
	public String getUpdatedip() {
		return this.updatedip;
	}

	public void setUpdatedip(String updatedip) {
		this.updatedip = updatedip;
	}

}
