package com.leonia.wellness.idao;

import java.util.List;
import java.util.Set;

import com.leonia.wellness.dto.Pagination;
import com.leonia.wellness.dto.StaffSkillsData;
import com.leonia.wellness.dto.TaxDetails;
import com.leonia.wellness.entity.Billinginstructionmaster;
import com.leonia.wellness.entity.Businesssourcemaster;
import com.leonia.wellness.entity.Citymaster;
import com.leonia.wellness.entity.Corporatemaster;
import com.leonia.wellness.entity.Corporatetypemaster;
import com.leonia.wellness.entity.Countrymaster;
import com.leonia.wellness.entity.Creditlistmaster;
import com.leonia.wellness.entity.Departmentmaster;
import com.leonia.wellness.entity.Dropdowndetails;
import com.leonia.wellness.entity.Giftvouchermaster;
import com.leonia.wellness.entity.Marketingvouchermaster;
import com.leonia.wellness.entity.Membershipmaster;
import com.leonia.wellness.entity.Packagemaster;
import com.leonia.wellness.entity.Packageratemaster;
import com.leonia.wellness.entity.Packageservices;
import com.leonia.wellness.entity.Productratemaster;
import com.leonia.wellness.entity.Qualificationmaster;
import com.leonia.wellness.entity.Reasondetails;
import com.leonia.wellness.entity.Reasonmaster;
import com.leonia.wellness.entity.Roommaster;
import com.leonia.wellness.entity.Segmentmaster;
import com.leonia.wellness.entity.Servicegroupmaster;
import com.leonia.wellness.entity.Servicemaster;
import com.leonia.wellness.entity.Serviceratemaster;
import com.leonia.wellness.entity.Serviceroommaster;
import com.leonia.wellness.entity.Servicestaffmaster;
import com.leonia.wellness.entity.Skillmaster;
import com.leonia.wellness.entity.Staffmaster;
import com.leonia.wellness.entity.Staffskill;
import com.leonia.wellness.entity.Statemaster;
import com.leonia.wellness.entity.Stockgroupmaster;
import com.leonia.wellness.entity.Stockmaster;
import com.leonia.wellness.entity.Stocksubgroupmaster;
import com.leonia.wellness.entity.Taxmaster;
import com.leonia.wellness.entity.Taxstructuremaster;

public interface IMasterDAO {
	public List<Reasonmaster> getAppointmentCancelReasons();
	public Set<Reasondetails> getReasonsList(Integer reasonchildmasterid);
	public void addReason(Reasondetails reasons);
	public String saveReason(String reasonName, Integer reasonchildmasterId);
	public String reasonUpdate(Integer reasonchildmasterId, Integer reasonid, String reason);
	public String reasonDelete(Integer reasonchildmasterId, Integer reasonid, String reason);
	public List<Servicemaster> getServices();
	public String saveServiceRate(Integer serviceId, Integer taxStructureId, Serviceratemaster servicerate);
	public List<Serviceratemaster> serviceRateList();
	public List<Taxstructuremaster> getTaxStructure();
	public String saveTax(Taxmaster tax, String taxName);
	public List<Taxmaster> taxList();
	public List<Taxstructuremaster> taxStructureList();
	public List<Taxmaster> getTaxMasterList();
	public String saveTaxStructure(TaxDetails taxDetails);
	public List<TaxDetails> getTaxStructureList();
	public List<Stockmaster> getProducts();
	public String saveProductRate(Integer productId, Integer taxStructureId, Productratemaster productrate);
	public List<Productratemaster> productRateList();
	public List<Servicegroupmaster> getServiceGroups(String serviceName, int records);
	public List<Dropdowndetails> getGenders();
	public String saveService(Servicemaster serviceMaster);
	public String editService(Servicemaster serviceMaster);
	public String deleteService(Servicemaster serviceMaster);
	public List<Servicemaster> getServiceByName(String serviceName);
	public List<Servicegroupmaster> getServiceGroupList();
	public String saveServiceGroup(Servicegroupmaster serviceGroup);
	public String editServiceGroup(Servicegroupmaster serviceGroup);
	public String deleteServiceGroup(Servicegroupmaster serviceGroup);
	public List<Servicegroupmaster> getServiceGroupByName(String serviceGroupName);
	public String savePackage(String packagename, String[] serviceids);
	public List<Packageservices> getPackageServices();
	public String editPackage(String packagename, String[] serviceids, Integer packageid);
	public List<Packageservices> getPackageServicebyid(Integer packageid);
	public String saveStockGroup(Stockgroupmaster stockGroupMaster);
	public List<Stockgroupmaster> getStockGroupList();
	public String editStockGroup(Stockgroupmaster stockGroup);
	public String deleteStockGroup(Stockgroupmaster stockGroup);
	public List<Stockgroupmaster> getStockGroupByName(String stockGroupName);
	public List<Stockgroupmaster> getStockGroups();
	public String saveStockSubGroup(Stocksubgroupmaster stockSubGroup);
	public List<Stocksubgroupmaster> getStockSubGroupList();
	public String editStockSubGroup(Stocksubgroupmaster stockSubGroup);
	public String deleteStockSubGroup(Stocksubgroupmaster stockSubGroup);
	public List<Stocksubgroupmaster> getStockSubGroupByName(String stockSubGroupName);
	public List<Billinginstructionmaster> getBillingInstructionList();
	public String saveBillingInstruction(Billinginstructionmaster billingInstruction);
	public String editBillingInstruction(Billinginstructionmaster billingInstruction);
	public String deleteBillingInstruction(Billinginstructionmaster billingInstruction);
	public List<Billinginstructionmaster> searchBillingInstruction(String description);
	public List<Businesssourcemaster> getBusinessSourceList();
	public String saveBusinessSource(Businesssourcemaster businessSource);
	public String editBusinessSource(Businesssourcemaster businessSource);
	public String deleteBusinessSource(Businesssourcemaster businessSource);
	public List<Businesssourcemaster> getsearchBusinessSource(String description);
	public List<Giftvouchermaster> getGiftVoucherList();
	public String saveGiftVoucher(Giftvouchermaster giftVoucher);
	public List<Corporatemaster> getCorporateList();
	public List<Creditlistmaster> getCreditListDetails();
	public String saveCreditList(Creditlistmaster creditlistmaster);
	public String deleteCreditList(int parseInt);
	public List<Citymaster> getCities();
	public List<Statemaster> getStates();
	public List<Countrymaster> getCountries();
	public List<Departmentmaster> getDepartments();
	public List<String> getStateCountryByCity(Integer cityId);
	public List<Packagemaster> getPackages();
    public String saveServiceRoom(Serviceroommaster serviceroom);
	public List<Serviceroommaster> getServiceRoomList();
	public String editServiceRoom(Serviceroommaster serviceroom);
	public String deleteServiceRoom(Serviceroommaster serviceroom);
	public List<Serviceroommaster> getsearchServiceRoom(String serviceName);
	public String savePackageRate(Integer packageId, Integer taxStructureId, Packageratemaster packagerate);
	public List packageRateList();
	public List<Corporatetypemaster> getCorporateTypeList(String corporateName, int i);
	public String saveCorporateType(Corporatetypemaster corporateType);
	public String editCorporateType(Corporatetypemaster corporateType);
	public String deleteCorporateType(Corporatetypemaster corporateType);
	public String deletePackageRate(Integer packageId, Integer taxStructureId, Packageratemaster packagerate);
	public Packagemaster getPackageById(Integer packageid);
	public String deletePackage(Integer packageid);
	public String saveStaff(Staffmaster staff);
	public List<String> getServicesByPackageId(Integer packageId);
	public Pagination corporateCount(String corporateName);
	public List<Serviceratemaster> searchserviceRateList(String serviceName);
	public List<Taxmaster> searchTaxByName(String taxName);
	public String editTax(Taxmaster tax);
	public String deleteTax(Taxmaster tax);
	public List<Staffmaster> getStaffList();
	public Staffmaster fetchStaffWithId(Integer id);
	public String editStaff(Staffmaster staffMaster);
	public Pagination serviceCount(String serviceName);
	List<Taxmaster> getsearchTax(String taxName);
	public List<Departmentmaster> getDepartment(String departmentname);
    public void saveDepartment(Departmentmaster departmentmaster);
    public void updateDepartment(Departmentmaster departmentmaster);	
    public Departmentmaster editDepartment(Integer depId);
    public List<Departmentmaster> listDepartments(Departmentmaster departmentmaster, int i, String pageName, String serach);
	public Pagination deparmentCount(Departmentmaster departmentmaster, String pageName, String serach);
	public String saveSkills(Skillmaster skillmaster);
	public List<Skillmaster> getSkillslist();
	public String editSkills(Skillmaster skillmaster);	
	public String deleteSkills(Skillmaster skillmaster);
	public Pagination skillCount(String skillname);
	public List<Skillmaster> getByName(String skillname,int records);
	
	public String saveQualification(Qualificationmaster qualificationmaster);
    public List<Qualificationmaster> getQualifications();
    public String editQualifications(Qualificationmaster qualificationmaster);	
	public String deleteQualification(Qualificationmaster qualificationmaster);
	
	public List<Qualificationmaster> getQualificationByName(String qualification,int records);
	public Pagination qualifyCount(String qualification);
	
	public List<Marketingvouchermaster> getMarketingVoucher();
	public String saveMarketingvoucher(Marketingvouchermaster marketvoucher);	
	
	
	public List<Marketingvouchermaster> getMvoucherByName(String mcompany,int records);
    public Pagination marketCount(String mcompany);
    
	public String saveRoom(Roommaster room);
	public List<Roommaster>getRooms();
	public String editRoom(Roommaster room);
	public List<Roommaster> getRoomsByNum(Integer roomnum,int records);
	public Pagination roomCount(Integer roomnum);
	public String deleteRoom(Roommaster room);
	public String saveSegment(Segmentmaster segment);
	public List<Segmentmaster>getSegment();
	public String editSegment(Segmentmaster segment);
	public String deleteSegment(Segmentmaster segment);
	public List<Segmentmaster> getSegmentByName(String segname,int records);
	public Pagination segmentCount(String segname);
	public String saveServiceStaff(Servicestaffmaster servicestaff);
	public List<Servicestaffmaster> getServiceStaffList();
	public List<Staffmaster> getStaff();
	public String editServiceStaff(Servicestaffmaster servicestaff);
	public String deleteServiceStaff(Servicestaffmaster servicestaff);
	public List<Servicestaffmaster> getsearchServiceStaff(String serviceName,int records);
	public Pagination serviceStaffCount(String serviceName);
    public List<Skillmaster> getSkills();
	Integer getskillid(String stockname);
	public void saveStaffSkills(List<StaffSkillsData> sfs);
	public Set<Staffskill> getSkill1(Integer staffId);
	public List<Membershipmaster> getmembershipList();
	public String saveMemberShip(Membershipmaster membershipmaster, String id);
	public List editvalue(Membershipmaster membershipmaster, String memberid);
	public List<Membershipmaster> searchByMemberName(String membername);
	public List<Corporatemaster> getCorporateList1();
	
	public List<Corporatemaster> getSearchByName(String corporatename);
	public String saveCorporateMaster(Corporatemaster corporatemaster, String corporateid);
	public List<Corporatetypemaster> getCorporateTypeList();


}
