<%@ page isELIgnored="false"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>

<div class="container-fluid">
	<div class="row">
		<div class="col-lg-12">
			<h1 class="page-header"></h1>
		</div>
	</div>
	<div class="row"></div>
		<div class="col-lg-12">
			<div class="panel panel-default">
				<div class="panel-heading">
					<h3 class="panel-title">Tickets</h3>
				</div>
				 
				<div class="panel-body">
					<div class="col-md-12">
						
						<form class="form-inline" action="displayTickets" method="post" id="ticketsList">
						<div class="form-group">
						<center>
						<label for="email">FromDate</label>
                        <input type="date" class="form-control" id="fromdate" name="fromdate" required="required" value="${fromdate}"/>
                        <label for="email">ToDate</label>
                        <input type="date" class="form-control" id="todate" name="todate" required="required" value="${todate}"/>
                    </div>
                     <button type="submit" class="btn btn-primary btn-sm" >Search</button><br><br><br>
                 </center>
                 </form>
                </div>
						
					<table  id="EditTable" class="table table-bordered table-hover">
							<thead>
									<tr>
										<th>AutoGeneratedTickets</th>
										<th>ManualTickets</th>
										<th></th>
									</tr>
								</thead>
								   <tr><td>${acount}</td>
								   <td>${mcount}</td></tr>
								 </table>
								 
							</div>
                          </div>
			            </div>
		</div>
		
<script >
var today = new Date().toISOString().split('T')[0];
document.getElementsByName("date")[0].setAttribute('max', today);
</script>
